// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"time"

	"github.com/MoScenix/mes/app/bff/biz/dal"
	"github.com/MoScenix/mes/app/bff/biz/router"
	"github.com/MoScenix/mes/app/bff/conf"
	"github.com/MoScenix/mes/app/bff/infra/rpc"
	"github.com/MoScenix/mes/app/bff/middleware"
	"github.com/MoScenix/mes/common/mtl"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
	kitexlogrus "github.com/kitex-contrib/obs-opentelemetry/logging/logrus"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

func main() {
	// init dal
	godotenv.Load()
	tp := mtl.TraceInit(conf.GetConf().Hertz.Service)
	defer tp.Shutdown(context.Background())
	dal.Init()
	address := conf.GetConf().Hertz.Address
	tracer, traceCfg := hertztracing.NewServerTracer()
	h := server.New(
		tracer,
		server.WithHostPorts(address),
		server.WithMaxRequestBodySize(conf.GetConf().Hertz.MaxRequestBodySize),
	)
	rpc.Init()
	registerMiddleware(h, traceCfg)

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})
	h.StaticFS(conf.StaticRoute(), &app.FS{
		Root:        conf.StaticRoot(),
		PathRewrite: app.NewPathSlashesStripper(conf.StaticRouteStripSlashes()),
	})
	router.GeneratedRegister(h)

	h.Spin()
}

func registerMiddleware(h *server.Hertz, traceCfg *hertztracing.Config) {
	store, err := redis.NewStore(100, "tcp", conf.GetConf().Redis.Address, conf.GetConf().Redis.Password, []byte(os.Getenv("SESSION_SECRET")))
	if err != nil {
		panic(err)
	}
	store.Options(sessions.Options{MaxAge: 86400, Path: "/"})
	rs, err := redis.GetRedisStore(store)
	if err == nil {
		rs.SetSerializer(sessions.JSONSerializer{})
	}
	h.Use(hertztracing.ServerMiddleware(traceCfg))
	h.Use(sessions.New("moscenix", store))
	// log
	logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	klog.SetLogger(kitexlogrus.NewLogger())
	klog.SetLevel(klog.Level(conf.LogLevel()))
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: time.Minute,
	}
	hlog.SetOutput(asyncWriter)
	klog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	middleware.Register(h)
}
