// Code generated by Kitex v0.9.1. DO NOT EDIT.

package documentservice

import (
	"context"
	"errors"

	document "github.com/MoScenix/mes/rpc_gen/kitex_gen/document"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ParsePDFToText": kitex.NewMethodInfo(
		parsePDFToTextHandler,
		newParsePDFToTextArgs,
		newParsePDFToTextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"IndexTextFile": kitex.NewMethodInfo(
		indexTextFileHandler,
		newIndexTextFileArgs,
		newIndexTextFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchFile": kitex.NewMethodInfo(
		searchFileHandler,
		newSearchFileArgs,
		newSearchFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteProjectFileData": kitex.NewMethodInfo(
		deleteProjectFileDataHandler,
		newDeleteProjectFileDataArgs,
		newDeleteProjectFileDataResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	documentServiceServiceInfo                = NewServiceInfo()
	documentServiceServiceInfoForClient       = NewServiceInfoForClient()
	documentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return documentServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return documentServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return documentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DocumentService"
	handlerType := (*document.DocumentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "document",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func parsePDFToTextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.ParsePDFToTextReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).ParsePDFToText(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ParsePDFToTextArgs:
		success, err := handler.(document.DocumentService).ParsePDFToText(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ParsePDFToTextResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newParsePDFToTextArgs() interface{} {
	return &ParsePDFToTextArgs{}
}

func newParsePDFToTextResult() interface{} {
	return &ParsePDFToTextResult{}
}

type ParsePDFToTextArgs struct {
	Req *document.ParsePDFToTextReq
}

func (p *ParsePDFToTextArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.ParsePDFToTextReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ParsePDFToTextArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ParsePDFToTextArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ParsePDFToTextArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ParsePDFToTextArgs) Unmarshal(in []byte) error {
	msg := new(document.ParsePDFToTextReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ParsePDFToTextArgs_Req_DEFAULT *document.ParsePDFToTextReq

func (p *ParsePDFToTextArgs) GetReq() *document.ParsePDFToTextReq {
	if !p.IsSetReq() {
		return ParsePDFToTextArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ParsePDFToTextArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ParsePDFToTextArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ParsePDFToTextResult struct {
	Success *document.ParsePDFToTextResp
}

var ParsePDFToTextResult_Success_DEFAULT *document.ParsePDFToTextResp

func (p *ParsePDFToTextResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.ParsePDFToTextResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ParsePDFToTextResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ParsePDFToTextResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ParsePDFToTextResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ParsePDFToTextResult) Unmarshal(in []byte) error {
	msg := new(document.ParsePDFToTextResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ParsePDFToTextResult) GetSuccess() *document.ParsePDFToTextResp {
	if !p.IsSetSuccess() {
		return ParsePDFToTextResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ParsePDFToTextResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.ParsePDFToTextResp)
}

func (p *ParsePDFToTextResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ParsePDFToTextResult) GetResult() interface{} {
	return p.Success
}

func indexTextFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.IndexTextFileReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).IndexTextFile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *IndexTextFileArgs:
		success, err := handler.(document.DocumentService).IndexTextFile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*IndexTextFileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newIndexTextFileArgs() interface{} {
	return &IndexTextFileArgs{}
}

func newIndexTextFileResult() interface{} {
	return &IndexTextFileResult{}
}

type IndexTextFileArgs struct {
	Req *document.IndexTextFileReq
}

func (p *IndexTextFileArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.IndexTextFileReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *IndexTextFileArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *IndexTextFileArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *IndexTextFileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *IndexTextFileArgs) Unmarshal(in []byte) error {
	msg := new(document.IndexTextFileReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var IndexTextFileArgs_Req_DEFAULT *document.IndexTextFileReq

func (p *IndexTextFileArgs) GetReq() *document.IndexTextFileReq {
	if !p.IsSetReq() {
		return IndexTextFileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *IndexTextFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IndexTextFileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type IndexTextFileResult struct {
	Success *document.IndexTextFileResp
}

var IndexTextFileResult_Success_DEFAULT *document.IndexTextFileResp

func (p *IndexTextFileResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.IndexTextFileResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *IndexTextFileResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *IndexTextFileResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *IndexTextFileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *IndexTextFileResult) Unmarshal(in []byte) error {
	msg := new(document.IndexTextFileResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *IndexTextFileResult) GetSuccess() *document.IndexTextFileResp {
	if !p.IsSetSuccess() {
		return IndexTextFileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *IndexTextFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.IndexTextFileResp)
}

func (p *IndexTextFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IndexTextFileResult) GetResult() interface{} {
	return p.Success
}

func searchFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.SearchFileReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).SearchFile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchFileArgs:
		success, err := handler.(document.DocumentService).SearchFile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchFileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchFileArgs() interface{} {
	return &SearchFileArgs{}
}

func newSearchFileResult() interface{} {
	return &SearchFileResult{}
}

type SearchFileArgs struct {
	Req *document.SearchFileReq
}

func (p *SearchFileArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.SearchFileReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SearchFileArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SearchFileArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SearchFileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchFileArgs) Unmarshal(in []byte) error {
	msg := new(document.SearchFileReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchFileArgs_Req_DEFAULT *document.SearchFileReq

func (p *SearchFileArgs) GetReq() *document.SearchFileReq {
	if !p.IsSetReq() {
		return SearchFileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchFileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchFileResult struct {
	Success *document.SearchFileResp
}

var SearchFileResult_Success_DEFAULT *document.SearchFileResp

func (p *SearchFileResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.SearchFileResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SearchFileResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SearchFileResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SearchFileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchFileResult) Unmarshal(in []byte) error {
	msg := new(document.SearchFileResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchFileResult) GetSuccess() *document.SearchFileResp {
	if !p.IsSetSuccess() {
		return SearchFileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.SearchFileResp)
}

func (p *SearchFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchFileResult) GetResult() interface{} {
	return p.Success
}

func deleteProjectFileDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.DeleteProjectFileDataReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).DeleteProjectFileData(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteProjectFileDataArgs:
		success, err := handler.(document.DocumentService).DeleteProjectFileData(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteProjectFileDataResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteProjectFileDataArgs() interface{} {
	return &DeleteProjectFileDataArgs{}
}

func newDeleteProjectFileDataResult() interface{} {
	return &DeleteProjectFileDataResult{}
}

type DeleteProjectFileDataArgs struct {
	Req *document.DeleteProjectFileDataReq
}

func (p *DeleteProjectFileDataArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.DeleteProjectFileDataReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteProjectFileDataArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteProjectFileDataArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteProjectFileDataArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteProjectFileDataArgs) Unmarshal(in []byte) error {
	msg := new(document.DeleteProjectFileDataReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteProjectFileDataArgs_Req_DEFAULT *document.DeleteProjectFileDataReq

func (p *DeleteProjectFileDataArgs) GetReq() *document.DeleteProjectFileDataReq {
	if !p.IsSetReq() {
		return DeleteProjectFileDataArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteProjectFileDataArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteProjectFileDataArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteProjectFileDataResult struct {
	Success *document.DeleteProjectFileDataResp
}

var DeleteProjectFileDataResult_Success_DEFAULT *document.DeleteProjectFileDataResp

func (p *DeleteProjectFileDataResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.DeleteProjectFileDataResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteProjectFileDataResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteProjectFileDataResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteProjectFileDataResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteProjectFileDataResult) Unmarshal(in []byte) error {
	msg := new(document.DeleteProjectFileDataResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteProjectFileDataResult) GetSuccess() *document.DeleteProjectFileDataResp {
	if !p.IsSetSuccess() {
		return DeleteProjectFileDataResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteProjectFileDataResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.DeleteProjectFileDataResp)
}

func (p *DeleteProjectFileDataResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteProjectFileDataResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ParsePDFToText(ctx context.Context, Req *document.ParsePDFToTextReq) (r *document.ParsePDFToTextResp, err error) {
	var _args ParsePDFToTextArgs
	_args.Req = Req
	var _result ParsePDFToTextResult
	if err = p.c.Call(ctx, "ParsePDFToText", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IndexTextFile(ctx context.Context, Req *document.IndexTextFileReq) (r *document.IndexTextFileResp, err error) {
	var _args IndexTextFileArgs
	_args.Req = Req
	var _result IndexTextFileResult
	if err = p.c.Call(ctx, "IndexTextFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchFile(ctx context.Context, Req *document.SearchFileReq) (r *document.SearchFileResp, err error) {
	var _args SearchFileArgs
	_args.Req = Req
	var _result SearchFileResult
	if err = p.c.Call(ctx, "SearchFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteProjectFileData(ctx context.Context, Req *document.DeleteProjectFileDataReq) (r *document.DeleteProjectFileDataResp, err error) {
	var _args DeleteProjectFileDataArgs
	_args.Req = Req
	var _result DeleteProjectFileDataResult
	if err = p.c.Call(ctx, "DeleteProjectFileData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
