# docker_files/DockerFile.document
FROM golang:1.25.5

WORKDIR /usr/src/gomall

ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=sum.golang.google.cn
ENV GOTOOLCHAIN=local
ENV GOWORK=off

COPY app/document/go.mod app/document/go.sum ./app/document/
COPY rpc_gen ./rpc_gen
COPY common ./common

RUN cd app/document && go mod download && go mod verify

COPY app/document ./app/document

RUN cd app/document && go build -mod=readonly -v -o server
RUN set -eux; \
  if [ -f /etc/apt/sources.list.d/debian.sources ]; then \
    sed -i \
      -e 's#http://deb.debian.org/debian-security#https://mirrors.aliyun.com/debian-security#g' \
      -e 's#https://deb.debian.org/debian-security#https://mirrors.aliyun.com/debian-security#g' \
      -e 's#http://deb.debian.org/debian#https://mirrors.aliyun.com/debian#g' \
      -e 's#https://deb.debian.org/debian#https://mirrors.aliyun.com/debian#g' \
      /etc/apt/sources.list.d/debian.sources; \
  fi; \
  if [ -f /etc/apt/sources.list ]; then \
    sed -i \
      -e 's#http://deb.debian.org/debian-security#https://mirrors.aliyun.com/debian-security#g' \
      -e 's#https://deb.debian.org/debian-security#https://mirrors.aliyun.com/debian-security#g' \
      -e 's#http://deb.debian.org/debian#https://mirrors.aliyun.com/debian#g' \
      -e 's#https://deb.debian.org/debian#https://mirrors.aliyun.com/debian#g' \
      /etc/apt/sources.list; \
  fi; \
  echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    ca-certificates \
    fonts-noto-cjk \
    poppler-utils; \
  rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/gomall/app/document
EXPOSE 8888
CMD ["./server"]
