# docker_files/DockerFile.user
FROM golang:1.25.5

WORKDIR /usr/src/gomall

ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=sum.golang.google.cn
ENV GOTOOLCHAIN=local
ENV GOWORK=off

COPY app/user/go.mod app/user/go.sum ./app/user/
COPY rpc_gen ./rpc_gen
COPY common ./common

RUN cd app/user && go mod download && go mod verify

COPY app/user ./app/user

RUN cd app/user && go build -mod=readonly -v -o server

WORKDIR /usr/src/gomall/app/user
EXPOSE 8888
CMD ["./server"]
