// Code generated by Kitex v0.9.1. DO NOT EDIT.

package workorderservice

import (
	"context"
	workorder "github.com/MoScenix/mes/rpc_gen/kitex_gen/workorder"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateWorkOrder(ctx context.Context, Req *workorder.CreateWorkOrderReq, callOptions ...callopt.Option) (r *workorder.CreateWorkOrderResp, err error)
	UpdateWorkOrderDraft(ctx context.Context, Req *workorder.UpdateWorkOrderDraftReq, callOptions ...callopt.Option) (r *workorder.UpdateWorkOrderDraftResp, err error)
	DeleteWorkOrderDraft(ctx context.Context, Req *workorder.DeleteWorkOrderDraftReq, callOptions ...callopt.Option) (r *workorder.DeleteWorkOrderDraftResp, err error)
	SubmitWorkOrder(ctx context.Context, Req *workorder.SubmitWorkOrderReq, callOptions ...callopt.Option) (r *workorder.SubmitWorkOrderResp, err error)
	GetWorkOrder(ctx context.Context, Req *workorder.GetWorkOrderReq, callOptions ...callopt.Option) (r *workorder.GetWorkOrderResp, err error)
	ListWorkOrder(ctx context.Context, Req *workorder.ListWorkOrderReq, callOptions ...callopt.Option) (r *workorder.ListWorkOrderResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kWorkOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kWorkOrderServiceClient struct {
	*kClient
}

func (p *kWorkOrderServiceClient) CreateWorkOrder(ctx context.Context, Req *workorder.CreateWorkOrderReq, callOptions ...callopt.Option) (r *workorder.CreateWorkOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateWorkOrder(ctx, Req)
}

func (p *kWorkOrderServiceClient) UpdateWorkOrderDraft(ctx context.Context, Req *workorder.UpdateWorkOrderDraftReq, callOptions ...callopt.Option) (r *workorder.UpdateWorkOrderDraftResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateWorkOrderDraft(ctx, Req)
}

func (p *kWorkOrderServiceClient) DeleteWorkOrderDraft(ctx context.Context, Req *workorder.DeleteWorkOrderDraftReq, callOptions ...callopt.Option) (r *workorder.DeleteWorkOrderDraftResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteWorkOrderDraft(ctx, Req)
}

func (p *kWorkOrderServiceClient) SubmitWorkOrder(ctx context.Context, Req *workorder.SubmitWorkOrderReq, callOptions ...callopt.Option) (r *workorder.SubmitWorkOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubmitWorkOrder(ctx, Req)
}

func (p *kWorkOrderServiceClient) GetWorkOrder(ctx context.Context, Req *workorder.GetWorkOrderReq, callOptions ...callopt.Option) (r *workorder.GetWorkOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWorkOrder(ctx, Req)
}

func (p *kWorkOrderServiceClient) ListWorkOrder(ctx context.Context, Req *workorder.ListWorkOrderReq, callOptions ...callopt.Option) (r *workorder.ListWorkOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListWorkOrder(ctx, Req)
}
