// Code generated by Kitex v0.9.1. DO NOT EDIT.

package workorderservice

import (
	"context"
	"errors"
	workorder "github.com/MoScenix/mes/rpc_gen/kitex_gen/workorder"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateWorkOrder": kitex.NewMethodInfo(
		createWorkOrderHandler,
		newCreateWorkOrderArgs,
		newCreateWorkOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateWorkOrderDraft": kitex.NewMethodInfo(
		updateWorkOrderDraftHandler,
		newUpdateWorkOrderDraftArgs,
		newUpdateWorkOrderDraftResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteWorkOrderDraft": kitex.NewMethodInfo(
		deleteWorkOrderDraftHandler,
		newDeleteWorkOrderDraftArgs,
		newDeleteWorkOrderDraftResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SubmitWorkOrder": kitex.NewMethodInfo(
		submitWorkOrderHandler,
		newSubmitWorkOrderArgs,
		newSubmitWorkOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetWorkOrder": kitex.NewMethodInfo(
		getWorkOrderHandler,
		newGetWorkOrderArgs,
		newGetWorkOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListWorkOrder": kitex.NewMethodInfo(
		listWorkOrderHandler,
		newListWorkOrderArgs,
		newListWorkOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MarkWorkOrderRead": kitex.NewMethodInfo(
		markWorkOrderReadHandler,
		newMarkWorkOrderReadArgs,
		newMarkWorkOrderReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	workOrderServiceServiceInfo                = NewServiceInfo()
	workOrderServiceServiceInfoForClient       = NewServiceInfoForClient()
	workOrderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workOrderServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workOrderServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workOrderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkOrderService"
	handlerType := (*workorder.WorkOrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "workorder",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func createWorkOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.CreateWorkOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).CreateWorkOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateWorkOrderArgs:
		success, err := handler.(workorder.WorkOrderService).CreateWorkOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateWorkOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateWorkOrderArgs() interface{} {
	return &CreateWorkOrderArgs{}
}

func newCreateWorkOrderResult() interface{} {
	return &CreateWorkOrderResult{}
}

type CreateWorkOrderArgs struct {
	Req *workorder.CreateWorkOrderReq
}

func (p *CreateWorkOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.CreateWorkOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateWorkOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateWorkOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateWorkOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateWorkOrderArgs) Unmarshal(in []byte) error {
	msg := new(workorder.CreateWorkOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateWorkOrderArgs_Req_DEFAULT *workorder.CreateWorkOrderReq

func (p *CreateWorkOrderArgs) GetReq() *workorder.CreateWorkOrderReq {
	if !p.IsSetReq() {
		return CreateWorkOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateWorkOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateWorkOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateWorkOrderResult struct {
	Success *workorder.CreateWorkOrderResp
}

var CreateWorkOrderResult_Success_DEFAULT *workorder.CreateWorkOrderResp

func (p *CreateWorkOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.CreateWorkOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateWorkOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateWorkOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateWorkOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateWorkOrderResult) Unmarshal(in []byte) error {
	msg := new(workorder.CreateWorkOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateWorkOrderResult) GetSuccess() *workorder.CreateWorkOrderResp {
	if !p.IsSetSuccess() {
		return CreateWorkOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateWorkOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.CreateWorkOrderResp)
}

func (p *CreateWorkOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateWorkOrderResult) GetResult() interface{} {
	return p.Success
}

func updateWorkOrderDraftHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.UpdateWorkOrderDraftReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).UpdateWorkOrderDraft(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateWorkOrderDraftArgs:
		success, err := handler.(workorder.WorkOrderService).UpdateWorkOrderDraft(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateWorkOrderDraftResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateWorkOrderDraftArgs() interface{} {
	return &UpdateWorkOrderDraftArgs{}
}

func newUpdateWorkOrderDraftResult() interface{} {
	return &UpdateWorkOrderDraftResult{}
}

type UpdateWorkOrderDraftArgs struct {
	Req *workorder.UpdateWorkOrderDraftReq
}

func (p *UpdateWorkOrderDraftArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.UpdateWorkOrderDraftReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateWorkOrderDraftArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateWorkOrderDraftArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateWorkOrderDraftArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateWorkOrderDraftArgs) Unmarshal(in []byte) error {
	msg := new(workorder.UpdateWorkOrderDraftReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateWorkOrderDraftArgs_Req_DEFAULT *workorder.UpdateWorkOrderDraftReq

func (p *UpdateWorkOrderDraftArgs) GetReq() *workorder.UpdateWorkOrderDraftReq {
	if !p.IsSetReq() {
		return UpdateWorkOrderDraftArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateWorkOrderDraftArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateWorkOrderDraftArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateWorkOrderDraftResult struct {
	Success *workorder.UpdateWorkOrderDraftResp
}

var UpdateWorkOrderDraftResult_Success_DEFAULT *workorder.UpdateWorkOrderDraftResp

func (p *UpdateWorkOrderDraftResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.UpdateWorkOrderDraftResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateWorkOrderDraftResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateWorkOrderDraftResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateWorkOrderDraftResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateWorkOrderDraftResult) Unmarshal(in []byte) error {
	msg := new(workorder.UpdateWorkOrderDraftResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateWorkOrderDraftResult) GetSuccess() *workorder.UpdateWorkOrderDraftResp {
	if !p.IsSetSuccess() {
		return UpdateWorkOrderDraftResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateWorkOrderDraftResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.UpdateWorkOrderDraftResp)
}

func (p *UpdateWorkOrderDraftResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateWorkOrderDraftResult) GetResult() interface{} {
	return p.Success
}

func deleteWorkOrderDraftHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.DeleteWorkOrderDraftReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).DeleteWorkOrderDraft(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteWorkOrderDraftArgs:
		success, err := handler.(workorder.WorkOrderService).DeleteWorkOrderDraft(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteWorkOrderDraftResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteWorkOrderDraftArgs() interface{} {
	return &DeleteWorkOrderDraftArgs{}
}

func newDeleteWorkOrderDraftResult() interface{} {
	return &DeleteWorkOrderDraftResult{}
}

type DeleteWorkOrderDraftArgs struct {
	Req *workorder.DeleteWorkOrderDraftReq
}

func (p *DeleteWorkOrderDraftArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.DeleteWorkOrderDraftReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteWorkOrderDraftArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteWorkOrderDraftArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteWorkOrderDraftArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteWorkOrderDraftArgs) Unmarshal(in []byte) error {
	msg := new(workorder.DeleteWorkOrderDraftReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteWorkOrderDraftArgs_Req_DEFAULT *workorder.DeleteWorkOrderDraftReq

func (p *DeleteWorkOrderDraftArgs) GetReq() *workorder.DeleteWorkOrderDraftReq {
	if !p.IsSetReq() {
		return DeleteWorkOrderDraftArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteWorkOrderDraftArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteWorkOrderDraftArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteWorkOrderDraftResult struct {
	Success *workorder.DeleteWorkOrderDraftResp
}

var DeleteWorkOrderDraftResult_Success_DEFAULT *workorder.DeleteWorkOrderDraftResp

func (p *DeleteWorkOrderDraftResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.DeleteWorkOrderDraftResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteWorkOrderDraftResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteWorkOrderDraftResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteWorkOrderDraftResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteWorkOrderDraftResult) Unmarshal(in []byte) error {
	msg := new(workorder.DeleteWorkOrderDraftResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteWorkOrderDraftResult) GetSuccess() *workorder.DeleteWorkOrderDraftResp {
	if !p.IsSetSuccess() {
		return DeleteWorkOrderDraftResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteWorkOrderDraftResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.DeleteWorkOrderDraftResp)
}

func (p *DeleteWorkOrderDraftResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteWorkOrderDraftResult) GetResult() interface{} {
	return p.Success
}

func submitWorkOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.SubmitWorkOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).SubmitWorkOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SubmitWorkOrderArgs:
		success, err := handler.(workorder.WorkOrderService).SubmitWorkOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SubmitWorkOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSubmitWorkOrderArgs() interface{} {
	return &SubmitWorkOrderArgs{}
}

func newSubmitWorkOrderResult() interface{} {
	return &SubmitWorkOrderResult{}
}

type SubmitWorkOrderArgs struct {
	Req *workorder.SubmitWorkOrderReq
}

func (p *SubmitWorkOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.SubmitWorkOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SubmitWorkOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SubmitWorkOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SubmitWorkOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SubmitWorkOrderArgs) Unmarshal(in []byte) error {
	msg := new(workorder.SubmitWorkOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SubmitWorkOrderArgs_Req_DEFAULT *workorder.SubmitWorkOrderReq

func (p *SubmitWorkOrderArgs) GetReq() *workorder.SubmitWorkOrderReq {
	if !p.IsSetReq() {
		return SubmitWorkOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SubmitWorkOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SubmitWorkOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SubmitWorkOrderResult struct {
	Success *workorder.SubmitWorkOrderResp
}

var SubmitWorkOrderResult_Success_DEFAULT *workorder.SubmitWorkOrderResp

func (p *SubmitWorkOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.SubmitWorkOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SubmitWorkOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SubmitWorkOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SubmitWorkOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SubmitWorkOrderResult) Unmarshal(in []byte) error {
	msg := new(workorder.SubmitWorkOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SubmitWorkOrderResult) GetSuccess() *workorder.SubmitWorkOrderResp {
	if !p.IsSetSuccess() {
		return SubmitWorkOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SubmitWorkOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.SubmitWorkOrderResp)
}

func (p *SubmitWorkOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SubmitWorkOrderResult) GetResult() interface{} {
	return p.Success
}

func getWorkOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.GetWorkOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).GetWorkOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetWorkOrderArgs:
		success, err := handler.(workorder.WorkOrderService).GetWorkOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetWorkOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetWorkOrderArgs() interface{} {
	return &GetWorkOrderArgs{}
}

func newGetWorkOrderResult() interface{} {
	return &GetWorkOrderResult{}
}

type GetWorkOrderArgs struct {
	Req *workorder.GetWorkOrderReq
}

func (p *GetWorkOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.GetWorkOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetWorkOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetWorkOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetWorkOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetWorkOrderArgs) Unmarshal(in []byte) error {
	msg := new(workorder.GetWorkOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetWorkOrderArgs_Req_DEFAULT *workorder.GetWorkOrderReq

func (p *GetWorkOrderArgs) GetReq() *workorder.GetWorkOrderReq {
	if !p.IsSetReq() {
		return GetWorkOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetWorkOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetWorkOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetWorkOrderResult struct {
	Success *workorder.GetWorkOrderResp
}

var GetWorkOrderResult_Success_DEFAULT *workorder.GetWorkOrderResp

func (p *GetWorkOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.GetWorkOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetWorkOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetWorkOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetWorkOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetWorkOrderResult) Unmarshal(in []byte) error {
	msg := new(workorder.GetWorkOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetWorkOrderResult) GetSuccess() *workorder.GetWorkOrderResp {
	if !p.IsSetSuccess() {
		return GetWorkOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetWorkOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.GetWorkOrderResp)
}

func (p *GetWorkOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetWorkOrderResult) GetResult() interface{} {
	return p.Success
}

func listWorkOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.ListWorkOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).ListWorkOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListWorkOrderArgs:
		success, err := handler.(workorder.WorkOrderService).ListWorkOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListWorkOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListWorkOrderArgs() interface{} {
	return &ListWorkOrderArgs{}
}

func newListWorkOrderResult() interface{} {
	return &ListWorkOrderResult{}
}

type ListWorkOrderArgs struct {
	Req *workorder.ListWorkOrderReq
}

func (p *ListWorkOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.ListWorkOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListWorkOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListWorkOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListWorkOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListWorkOrderArgs) Unmarshal(in []byte) error {
	msg := new(workorder.ListWorkOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListWorkOrderArgs_Req_DEFAULT *workorder.ListWorkOrderReq

func (p *ListWorkOrderArgs) GetReq() *workorder.ListWorkOrderReq {
	if !p.IsSetReq() {
		return ListWorkOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListWorkOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListWorkOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListWorkOrderResult struct {
	Success *workorder.ListWorkOrderResp
}

var ListWorkOrderResult_Success_DEFAULT *workorder.ListWorkOrderResp

func (p *ListWorkOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.ListWorkOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListWorkOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListWorkOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListWorkOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListWorkOrderResult) Unmarshal(in []byte) error {
	msg := new(workorder.ListWorkOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListWorkOrderResult) GetSuccess() *workorder.ListWorkOrderResp {
	if !p.IsSetSuccess() {
		return ListWorkOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListWorkOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.ListWorkOrderResp)
}

func (p *ListWorkOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListWorkOrderResult) GetResult() interface{} {
	return p.Success
}

func markWorkOrderReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(workorder.MarkWorkOrderReadReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(workorder.WorkOrderService).MarkWorkOrderRead(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MarkWorkOrderReadArgs:
		success, err := handler.(workorder.WorkOrderService).MarkWorkOrderRead(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MarkWorkOrderReadResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMarkWorkOrderReadArgs() interface{} {
	return &MarkWorkOrderReadArgs{}
}

func newMarkWorkOrderReadResult() interface{} {
	return &MarkWorkOrderReadResult{}
}

type MarkWorkOrderReadArgs struct {
	Req *workorder.MarkWorkOrderReadReq
}

func (p *MarkWorkOrderReadArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(workorder.MarkWorkOrderReadReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MarkWorkOrderReadArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MarkWorkOrderReadArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MarkWorkOrderReadArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MarkWorkOrderReadArgs) Unmarshal(in []byte) error {
	msg := new(workorder.MarkWorkOrderReadReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MarkWorkOrderReadArgs_Req_DEFAULT *workorder.MarkWorkOrderReadReq

func (p *MarkWorkOrderReadArgs) GetReq() *workorder.MarkWorkOrderReadReq {
	if !p.IsSetReq() {
		return MarkWorkOrderReadArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MarkWorkOrderReadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MarkWorkOrderReadArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MarkWorkOrderReadResult struct {
	Success *workorder.MarkWorkOrderReadResp
}

var MarkWorkOrderReadResult_Success_DEFAULT *workorder.MarkWorkOrderReadResp

func (p *MarkWorkOrderReadResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(workorder.MarkWorkOrderReadResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MarkWorkOrderReadResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MarkWorkOrderReadResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MarkWorkOrderReadResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MarkWorkOrderReadResult) Unmarshal(in []byte) error {
	msg := new(workorder.MarkWorkOrderReadResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MarkWorkOrderReadResult) GetSuccess() *workorder.MarkWorkOrderReadResp {
	if !p.IsSetSuccess() {
		return MarkWorkOrderReadResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MarkWorkOrderReadResult) SetSuccess(x interface{}) {
	p.Success = x.(*workorder.MarkWorkOrderReadResp)
}

func (p *MarkWorkOrderReadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MarkWorkOrderReadResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateWorkOrder(ctx context.Context, Req *workorder.CreateWorkOrderReq) (r *workorder.CreateWorkOrderResp, err error) {
	var _args CreateWorkOrderArgs
	_args.Req = Req
	var _result CreateWorkOrderResult
	if err = p.c.Call(ctx, "CreateWorkOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateWorkOrderDraft(ctx context.Context, Req *workorder.UpdateWorkOrderDraftReq) (r *workorder.UpdateWorkOrderDraftResp, err error) {
	var _args UpdateWorkOrderDraftArgs
	_args.Req = Req
	var _result UpdateWorkOrderDraftResult
	if err = p.c.Call(ctx, "UpdateWorkOrderDraft", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteWorkOrderDraft(ctx context.Context, Req *workorder.DeleteWorkOrderDraftReq) (r *workorder.DeleteWorkOrderDraftResp, err error) {
	var _args DeleteWorkOrderDraftArgs
	_args.Req = Req
	var _result DeleteWorkOrderDraftResult
	if err = p.c.Call(ctx, "DeleteWorkOrderDraft", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SubmitWorkOrder(ctx context.Context, Req *workorder.SubmitWorkOrderReq) (r *workorder.SubmitWorkOrderResp, err error) {
	var _args SubmitWorkOrderArgs
	_args.Req = Req
	var _result SubmitWorkOrderResult
	if err = p.c.Call(ctx, "SubmitWorkOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetWorkOrder(ctx context.Context, Req *workorder.GetWorkOrderReq) (r *workorder.GetWorkOrderResp, err error) {
	var _args GetWorkOrderArgs
	_args.Req = Req
	var _result GetWorkOrderResult
	if err = p.c.Call(ctx, "GetWorkOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListWorkOrder(ctx context.Context, Req *workorder.ListWorkOrderReq) (r *workorder.ListWorkOrderResp, err error) {
	var _args ListWorkOrderArgs
	_args.Req = Req
	var _result ListWorkOrderResult
	if err = p.c.Call(ctx, "ListWorkOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkWorkOrderRead(ctx context.Context, Req *workorder.MarkWorkOrderReadReq) (r *workorder.MarkWorkOrderReadResp, err error) {
	var _args MarkWorkOrderReadArgs
	_args.Req = Req
	var _result MarkWorkOrderReadResult
	if err = p.c.Call(ctx, "MarkWorkOrderRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
