// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	app "github.com/MoScenix/mes/app/bff/biz/router/app"
	mes "github.com/MoScenix/mes/app/bff/biz/router/mes"
	user "github.com/MoScenix/mes/app/bff/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	mes.Register(r)

	app.Register(r)

	user.Register(r)
}
