// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package workorder

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *WorkOrderInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_WorkOrderInfo[number], err)
}

func (x *WorkOrderInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FromUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ToUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Description, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Status = WorkOrderStatus(v)
	return offset, nil
}

func (x *WorkOrderInfo) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.ReadStatus = WorkOrderReadStatus(v)
	return offset, nil
}

func (x *WorkOrderInfo) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.Name, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateWorkOrderReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateWorkOrderReq[number], err)
}

func (x *CreateWorkOrderReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.FromUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateWorkOrderReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ToUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateWorkOrderReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Description, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateWorkOrderReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Name, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateWorkOrderResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateWorkOrderResp[number], err)
}

func (x *CreateWorkOrderResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateWorkOrderDraftReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateWorkOrderDraftReq[number], err)
}

func (x *UpdateWorkOrderDraftReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateWorkOrderDraftReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FromUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateWorkOrderDraftReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ToUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateWorkOrderDraftReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Description, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateWorkOrderDraftReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.Name, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateWorkOrderDraftResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateWorkOrderDraftResp[number], err)
}

func (x *UpdateWorkOrderDraftResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *DeleteWorkOrderDraftReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteWorkOrderDraftReq[number], err)
}

func (x *DeleteWorkOrderDraftReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteWorkOrderDraftResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteWorkOrderDraftResp[number], err)
}

func (x *DeleteWorkOrderDraftResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *SubmitWorkOrderReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SubmitWorkOrderReq[number], err)
}

func (x *SubmitWorkOrderReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SubmitWorkOrderResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SubmitWorkOrderResp[number], err)
}

func (x *SubmitWorkOrderResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *GetWorkOrderReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetWorkOrderReq[number], err)
}

func (x *GetWorkOrderReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GetWorkOrderResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetWorkOrderResp[number], err)
}

func (x *GetWorkOrderResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v WorkOrderInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.WorkOrder = &v
	return offset, nil
}

func (x *ListWorkOrderReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 11:
		offset, err = x.fastReadField11(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListWorkOrderReq[number], err)
}

func (x *ListWorkOrderReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.PageNum, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.IsTo, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.IsUnread, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.SinceTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.RecentSeconds, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.CursorUpdatedAt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.CursorId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.NamePrefix, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListWorkOrderReq) fastReadField11(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Status = WorkOrderStatus(v)
	return offset, nil
}

func (x *ListWorkOrderResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListWorkOrderResp[number], err)
}

func (x *ListWorkOrderResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v WorkOrderInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.WorkOrderList = append(x.WorkOrderList, &v)
	return offset, nil
}

func (x *ListWorkOrderResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListWorkOrderResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.HasMore, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ListWorkOrderResp) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.NextCursorUpdatedAt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListWorkOrderResp) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.NextCursorId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *MarkWorkOrderReadReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_MarkWorkOrderReadReq[number], err)
}

func (x *MarkWorkOrderReadReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *MarkWorkOrderReadResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_MarkWorkOrderReadResp[number], err)
}

func (x *MarkWorkOrderReadResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *WorkOrderInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	return offset
}

func (x *WorkOrderInfo) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *WorkOrderInfo) fastWriteField2(buf []byte) (offset int) {
	if x.FromUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetFromUserId())
	return offset
}

func (x *WorkOrderInfo) fastWriteField3(buf []byte) (offset int) {
	if x.ToUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetToUserId())
	return offset
}

func (x *WorkOrderInfo) fastWriteField4(buf []byte) (offset int) {
	if x.Description == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetDescription())
	return offset
}

func (x *WorkOrderInfo) fastWriteField5(buf []byte) (offset int) {
	if x.Status == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 5, int32(x.GetStatus()))
	return offset
}

func (x *WorkOrderInfo) fastWriteField6(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetCreateTime())
	return offset
}

func (x *WorkOrderInfo) fastWriteField7(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetUpdateTime())
	return offset
}

func (x *WorkOrderInfo) fastWriteField8(buf []byte) (offset int) {
	if x.ReadStatus == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 8, int32(x.GetReadStatus()))
	return offset
}

func (x *WorkOrderInfo) fastWriteField9(buf []byte) (offset int) {
	if x.Name == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 9, x.GetName())
	return offset
}

func (x *CreateWorkOrderReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *CreateWorkOrderReq) fastWriteField1(buf []byte) (offset int) {
	if x.FromUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetFromUserId())
	return offset
}

func (x *CreateWorkOrderReq) fastWriteField2(buf []byte) (offset int) {
	if x.ToUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetToUserId())
	return offset
}

func (x *CreateWorkOrderReq) fastWriteField3(buf []byte) (offset int) {
	if x.Description == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetDescription())
	return offset
}

func (x *CreateWorkOrderReq) fastWriteField4(buf []byte) (offset int) {
	if x.Name == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetName())
	return offset
}

func (x *CreateWorkOrderResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *CreateWorkOrderResp) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *UpdateWorkOrderDraftReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *UpdateWorkOrderDraftReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *UpdateWorkOrderDraftReq) fastWriteField2(buf []byte) (offset int) {
	if x.FromUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetFromUserId())
	return offset
}

func (x *UpdateWorkOrderDraftReq) fastWriteField3(buf []byte) (offset int) {
	if x.ToUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetToUserId())
	return offset
}

func (x *UpdateWorkOrderDraftReq) fastWriteField4(buf []byte) (offset int) {
	if x.Description == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetDescription())
	return offset
}

func (x *UpdateWorkOrderDraftReq) fastWriteField5(buf []byte) (offset int) {
	if x.Name == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetName())
	return offset
}

func (x *UpdateWorkOrderDraftResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *UpdateWorkOrderDraftResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *DeleteWorkOrderDraftReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteWorkOrderDraftReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteWorkOrderDraftResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteWorkOrderDraftResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *SubmitWorkOrderReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SubmitWorkOrderReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *SubmitWorkOrderResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SubmitWorkOrderResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *GetWorkOrderReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetWorkOrderReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GetWorkOrderResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetWorkOrderResp) fastWriteField1(buf []byte) (offset int) {
	if x.WorkOrder == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetWorkOrder())
	return offset
}

func (x *ListWorkOrderReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	offset += x.fastWriteField11(buf[offset:])
	return offset
}

func (x *ListWorkOrderReq) fastWriteField1(buf []byte) (offset int) {
	if x.PageNum == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetPageNum())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField2(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetPageSize())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField3(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetId())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField4(buf []byte) (offset int) {
	if !x.IsTo {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 4, x.GetIsTo())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField5(buf []byte) (offset int) {
	if !x.IsUnread {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 5, x.GetIsUnread())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField6(buf []byte) (offset int) {
	if x.SinceTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetSinceTime())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField7(buf []byte) (offset int) {
	if x.RecentSeconds == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 7, x.GetRecentSeconds())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField8(buf []byte) (offset int) {
	if x.CursorUpdatedAt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetCursorUpdatedAt())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField9(buf []byte) (offset int) {
	if x.CursorId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 9, x.GetCursorId())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField10(buf []byte) (offset int) {
	if x.NamePrefix == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 10, x.GetNamePrefix())
	return offset
}

func (x *ListWorkOrderReq) fastWriteField11(buf []byte) (offset int) {
	if x.Status == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 11, int32(x.GetStatus()))
	return offset
}

func (x *ListWorkOrderResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *ListWorkOrderResp) fastWriteField1(buf []byte) (offset int) {
	if x.WorkOrderList == nil {
		return offset
	}
	for i := range x.GetWorkOrderList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetWorkOrderList()[i])
	}
	return offset
}

func (x *ListWorkOrderResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *ListWorkOrderResp) fastWriteField3(buf []byte) (offset int) {
	if !x.HasMore {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 3, x.GetHasMore())
	return offset
}

func (x *ListWorkOrderResp) fastWriteField4(buf []byte) (offset int) {
	if x.NextCursorUpdatedAt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetNextCursorUpdatedAt())
	return offset
}

func (x *ListWorkOrderResp) fastWriteField5(buf []byte) (offset int) {
	if x.NextCursorId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 5, x.GetNextCursorId())
	return offset
}

func (x *MarkWorkOrderReadReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *MarkWorkOrderReadReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *MarkWorkOrderReadResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *MarkWorkOrderReadResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *WorkOrderInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	return n
}

func (x *WorkOrderInfo) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *WorkOrderInfo) sizeField2() (n int) {
	if x.FromUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetFromUserId())
	return n
}

func (x *WorkOrderInfo) sizeField3() (n int) {
	if x.ToUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetToUserId())
	return n
}

func (x *WorkOrderInfo) sizeField4() (n int) {
	if x.Description == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetDescription())
	return n
}

func (x *WorkOrderInfo) sizeField5() (n int) {
	if x.Status == 0 {
		return n
	}
	n += fastpb.SizeInt32(5, int32(x.GetStatus()))
	return n
}

func (x *WorkOrderInfo) sizeField6() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetCreateTime())
	return n
}

func (x *WorkOrderInfo) sizeField7() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetUpdateTime())
	return n
}

func (x *WorkOrderInfo) sizeField8() (n int) {
	if x.ReadStatus == 0 {
		return n
	}
	n += fastpb.SizeInt32(8, int32(x.GetReadStatus()))
	return n
}

func (x *WorkOrderInfo) sizeField9() (n int) {
	if x.Name == "" {
		return n
	}
	n += fastpb.SizeString(9, x.GetName())
	return n
}

func (x *CreateWorkOrderReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *CreateWorkOrderReq) sizeField1() (n int) {
	if x.FromUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetFromUserId())
	return n
}

func (x *CreateWorkOrderReq) sizeField2() (n int) {
	if x.ToUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetToUserId())
	return n
}

func (x *CreateWorkOrderReq) sizeField3() (n int) {
	if x.Description == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetDescription())
	return n
}

func (x *CreateWorkOrderReq) sizeField4() (n int) {
	if x.Name == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetName())
	return n
}

func (x *CreateWorkOrderResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *CreateWorkOrderResp) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *UpdateWorkOrderDraftReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *UpdateWorkOrderDraftReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *UpdateWorkOrderDraftReq) sizeField2() (n int) {
	if x.FromUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetFromUserId())
	return n
}

func (x *UpdateWorkOrderDraftReq) sizeField3() (n int) {
	if x.ToUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetToUserId())
	return n
}

func (x *UpdateWorkOrderDraftReq) sizeField4() (n int) {
	if x.Description == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetDescription())
	return n
}

func (x *UpdateWorkOrderDraftReq) sizeField5() (n int) {
	if x.Name == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetName())
	return n
}

func (x *UpdateWorkOrderDraftResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *UpdateWorkOrderDraftResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *DeleteWorkOrderDraftReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteWorkOrderDraftReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteWorkOrderDraftResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteWorkOrderDraftResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *SubmitWorkOrderReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SubmitWorkOrderReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *SubmitWorkOrderResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SubmitWorkOrderResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *GetWorkOrderReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetWorkOrderReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GetWorkOrderResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetWorkOrderResp) sizeField1() (n int) {
	if x.WorkOrder == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetWorkOrder())
	return n
}

func (x *ListWorkOrderReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	n += x.sizeField11()
	return n
}

func (x *ListWorkOrderReq) sizeField1() (n int) {
	if x.PageNum == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetPageNum())
	return n
}

func (x *ListWorkOrderReq) sizeField2() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetPageSize())
	return n
}

func (x *ListWorkOrderReq) sizeField3() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetId())
	return n
}

func (x *ListWorkOrderReq) sizeField4() (n int) {
	if !x.IsTo {
		return n
	}
	n += fastpb.SizeBool(4, x.GetIsTo())
	return n
}

func (x *ListWorkOrderReq) sizeField5() (n int) {
	if !x.IsUnread {
		return n
	}
	n += fastpb.SizeBool(5, x.GetIsUnread())
	return n
}

func (x *ListWorkOrderReq) sizeField6() (n int) {
	if x.SinceTime == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetSinceTime())
	return n
}

func (x *ListWorkOrderReq) sizeField7() (n int) {
	if x.RecentSeconds == 0 {
		return n
	}
	n += fastpb.SizeInt64(7, x.GetRecentSeconds())
	return n
}

func (x *ListWorkOrderReq) sizeField8() (n int) {
	if x.CursorUpdatedAt == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetCursorUpdatedAt())
	return n
}

func (x *ListWorkOrderReq) sizeField9() (n int) {
	if x.CursorId == 0 {
		return n
	}
	n += fastpb.SizeInt64(9, x.GetCursorId())
	return n
}

func (x *ListWorkOrderReq) sizeField10() (n int) {
	if x.NamePrefix == "" {
		return n
	}
	n += fastpb.SizeString(10, x.GetNamePrefix())
	return n
}

func (x *ListWorkOrderReq) sizeField11() (n int) {
	if x.Status == 0 {
		return n
	}
	n += fastpb.SizeInt32(11, int32(x.GetStatus()))
	return n
}

func (x *ListWorkOrderResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *ListWorkOrderResp) sizeField1() (n int) {
	if x.WorkOrderList == nil {
		return n
	}
	for i := range x.GetWorkOrderList() {
		n += fastpb.SizeMessage(1, x.GetWorkOrderList()[i])
	}
	return n
}

func (x *ListWorkOrderResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

func (x *ListWorkOrderResp) sizeField3() (n int) {
	if !x.HasMore {
		return n
	}
	n += fastpb.SizeBool(3, x.GetHasMore())
	return n
}

func (x *ListWorkOrderResp) sizeField4() (n int) {
	if x.NextCursorUpdatedAt == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetNextCursorUpdatedAt())
	return n
}

func (x *ListWorkOrderResp) sizeField5() (n int) {
	if x.NextCursorId == 0 {
		return n
	}
	n += fastpb.SizeInt64(5, x.GetNextCursorId())
	return n
}

func (x *MarkWorkOrderReadReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *MarkWorkOrderReadReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *MarkWorkOrderReadResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *MarkWorkOrderReadResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

var fieldIDToName_WorkOrderInfo = map[int32]string{
	1: "Id",
	2: "FromUserId",
	3: "ToUserId",
	4: "Description",
	5: "Status",
	6: "CreateTime",
	7: "UpdateTime",
	8: "ReadStatus",
	9: "Name",
}

var fieldIDToName_CreateWorkOrderReq = map[int32]string{
	1: "FromUserId",
	2: "ToUserId",
	3: "Description",
	4: "Name",
}

var fieldIDToName_CreateWorkOrderResp = map[int32]string{
	1: "Id",
}

var fieldIDToName_UpdateWorkOrderDraftReq = map[int32]string{
	1: "Id",
	2: "FromUserId",
	3: "ToUserId",
	4: "Description",
	5: "Name",
}

var fieldIDToName_UpdateWorkOrderDraftResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_DeleteWorkOrderDraftReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteWorkOrderDraftResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_SubmitWorkOrderReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_SubmitWorkOrderResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_GetWorkOrderReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_GetWorkOrderResp = map[int32]string{
	1: "WorkOrder",
}

var fieldIDToName_ListWorkOrderReq = map[int32]string{
	1:  "PageNum",
	2:  "PageSize",
	3:  "Id",
	4:  "IsTo",
	5:  "IsUnread",
	6:  "SinceTime",
	7:  "RecentSeconds",
	8:  "CursorUpdatedAt",
	9:  "CursorId",
	10: "NamePrefix",
	11: "Status",
}

var fieldIDToName_ListWorkOrderResp = map[int32]string{
	1: "WorkOrderList",
	2: "Total",
	3: "HasMore",
	4: "NextCursorUpdatedAt",
	5: "NextCursorId",
}

var fieldIDToName_MarkWorkOrderReadReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_MarkWorkOrderReadResp = map[int32]string{
	1: "Success",
}
