// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: workorder.proto

package workorder

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkOrderStatus int32

const (
	WorkOrderStatus_WORK_ORDER_STATUS_UNKNOWN   WorkOrderStatus = 0
	WorkOrderStatus_WORK_ORDER_STATUS_DRAFT     WorkOrderStatus = 1
	WorkOrderStatus_WORK_ORDER_STATUS_SUBMITTED WorkOrderStatus = 2
)

// Enum value maps for WorkOrderStatus.
var (
	WorkOrderStatus_name = map[int32]string{
		0: "WORK_ORDER_STATUS_UNKNOWN",
		1: "WORK_ORDER_STATUS_DRAFT",
		2: "WORK_ORDER_STATUS_SUBMITTED",
	}
	WorkOrderStatus_value = map[string]int32{
		"WORK_ORDER_STATUS_UNKNOWN":   0,
		"WORK_ORDER_STATUS_DRAFT":     1,
		"WORK_ORDER_STATUS_SUBMITTED": 2,
	}
)

func (x WorkOrderStatus) Enum() *WorkOrderStatus {
	p := new(WorkOrderStatus)
	*p = x
	return p
}

func (x WorkOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workorder_proto_enumTypes[0].Descriptor()
}

func (WorkOrderStatus) Type() protoreflect.EnumType {
	return &file_workorder_proto_enumTypes[0]
}

func (x WorkOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkOrderStatus.Descriptor instead.
func (WorkOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{0}
}

type WorkOrderReadStatus int32

const (
	WorkOrderReadStatus_WORK_ORDER_READ_STATUS_UNKNOWN WorkOrderReadStatus = 0
	WorkOrderReadStatus_WORK_ORDER_READ_STATUS_UNREAD  WorkOrderReadStatus = 1
	WorkOrderReadStatus_WORK_ORDER_READ_STATUS_READ    WorkOrderReadStatus = 2
)

// Enum value maps for WorkOrderReadStatus.
var (
	WorkOrderReadStatus_name = map[int32]string{
		0: "WORK_ORDER_READ_STATUS_UNKNOWN",
		1: "WORK_ORDER_READ_STATUS_UNREAD",
		2: "WORK_ORDER_READ_STATUS_READ",
	}
	WorkOrderReadStatus_value = map[string]int32{
		"WORK_ORDER_READ_STATUS_UNKNOWN": 0,
		"WORK_ORDER_READ_STATUS_UNREAD":  1,
		"WORK_ORDER_READ_STATUS_READ":    2,
	}
)

func (x WorkOrderReadStatus) Enum() *WorkOrderReadStatus {
	p := new(WorkOrderReadStatus)
	*p = x
	return p
}

func (x WorkOrderReadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkOrderReadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workorder_proto_enumTypes[1].Descriptor()
}

func (WorkOrderReadStatus) Type() protoreflect.EnumType {
	return &file_workorder_proto_enumTypes[1]
}

func (x WorkOrderReadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkOrderReadStatus.Descriptor instead.
func (WorkOrderReadStatus) EnumDescriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{1}
}

type WorkOrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId  int64               `protobuf:"varint,2,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	ToUserId    int64               `protobuf:"varint,3,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Description string              `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status      WorkOrderStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=workorder.WorkOrderStatus" json:"status,omitempty"`
	CreateTime  string              `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime  string              `protobuf:"bytes,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	ReadStatus  WorkOrderReadStatus `protobuf:"varint,8,opt,name=readStatus,proto3,enum=workorder.WorkOrderReadStatus" json:"readStatus,omitempty"`
	Name        string              `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *WorkOrderInfo) Reset() {
	*x = WorkOrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkOrderInfo) ProtoMessage() {}

func (x *WorkOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkOrderInfo.ProtoReflect.Descriptor instead.
func (*WorkOrderInfo) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{0}
}

func (x *WorkOrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkOrderInfo) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *WorkOrderInfo) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *WorkOrderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkOrderInfo) GetStatus() WorkOrderStatus {
	if x != nil {
		return x.Status
	}
	return WorkOrderStatus_WORK_ORDER_STATUS_UNKNOWN
}

func (x *WorkOrderInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *WorkOrderInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *WorkOrderInfo) GetReadStatus() WorkOrderReadStatus {
	if x != nil {
		return x.ReadStatus
	}
	return WorkOrderReadStatus_WORK_ORDER_READ_STATUS_UNKNOWN
}

func (x *WorkOrderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateWorkOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId  int64  `protobuf:"varint,1,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	ToUserId    int64  `protobuf:"varint,2,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateWorkOrderReq) Reset() {
	*x = CreateWorkOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkOrderReq) ProtoMessage() {}

func (x *CreateWorkOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkOrderReq.ProtoReflect.Descriptor instead.
func (*CreateWorkOrderReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkOrderReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *CreateWorkOrderReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *CreateWorkOrderReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkOrderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateWorkOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWorkOrderResp) Reset() {
	*x = CreateWorkOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkOrderResp) ProtoMessage() {}

func (x *CreateWorkOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkOrderResp.ProtoReflect.Descriptor instead.
func (*CreateWorkOrderResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWorkOrderResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateWorkOrderDraftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId  int64  `protobuf:"varint,2,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	ToUserId    int64  `protobuf:"varint,3,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Name        string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateWorkOrderDraftReq) Reset() {
	*x = UpdateWorkOrderDraftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorkOrderDraftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkOrderDraftReq) ProtoMessage() {}

func (x *UpdateWorkOrderDraftReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkOrderDraftReq.ProtoReflect.Descriptor instead.
func (*UpdateWorkOrderDraftReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWorkOrderDraftReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWorkOrderDraftReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *UpdateWorkOrderDraftReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *UpdateWorkOrderDraftReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWorkOrderDraftReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateWorkOrderDraftResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateWorkOrderDraftResp) Reset() {
	*x = UpdateWorkOrderDraftResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorkOrderDraftResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkOrderDraftResp) ProtoMessage() {}

func (x *UpdateWorkOrderDraftResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkOrderDraftResp.ProtoReflect.Descriptor instead.
func (*UpdateWorkOrderDraftResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWorkOrderDraftResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteWorkOrderDraftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteWorkOrderDraftReq) Reset() {
	*x = DeleteWorkOrderDraftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkOrderDraftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkOrderDraftReq) ProtoMessage() {}

func (x *DeleteWorkOrderDraftReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkOrderDraftReq.ProtoReflect.Descriptor instead.
func (*DeleteWorkOrderDraftReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWorkOrderDraftReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWorkOrderDraftResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteWorkOrderDraftResp) Reset() {
	*x = DeleteWorkOrderDraftResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkOrderDraftResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkOrderDraftResp) ProtoMessage() {}

func (x *DeleteWorkOrderDraftResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkOrderDraftResp.ProtoReflect.Descriptor instead.
func (*DeleteWorkOrderDraftResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWorkOrderDraftResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubmitWorkOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SubmitWorkOrderReq) Reset() {
	*x = SubmitWorkOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitWorkOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkOrderReq) ProtoMessage() {}

func (x *SubmitWorkOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkOrderReq.ProtoReflect.Descriptor instead.
func (*SubmitWorkOrderReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitWorkOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubmitWorkOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SubmitWorkOrderResp) Reset() {
	*x = SubmitWorkOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitWorkOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkOrderResp) ProtoMessage() {}

func (x *SubmitWorkOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkOrderResp.ProtoReflect.Descriptor instead.
func (*SubmitWorkOrderResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitWorkOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetWorkOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWorkOrderReq) Reset() {
	*x = GetWorkOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderReq) ProtoMessage() {}

func (x *GetWorkOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderReq.ProtoReflect.Descriptor instead.
func (*GetWorkOrderReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{9}
}

func (x *GetWorkOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWorkOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkOrder *WorkOrderInfo `protobuf:"bytes,1,opt,name=workOrder,proto3" json:"workOrder,omitempty"`
}

func (x *GetWorkOrderResp) Reset() {
	*x = GetWorkOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderResp) ProtoMessage() {}

func (x *GetWorkOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderResp.ProtoReflect.Descriptor instead.
func (*GetWorkOrderResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{10}
}

func (x *GetWorkOrderResp) GetWorkOrder() *WorkOrderInfo {
	if x != nil {
		return x.WorkOrder
	}
	return nil
}

type ListWorkOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum         int64           `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize        int64           `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Id              int64           `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	IsTo            bool            `protobuf:"varint,4,opt,name=isTo,proto3" json:"isTo,omitempty"`
	IsUnread        bool            `protobuf:"varint,5,opt,name=isUnread,proto3" json:"isUnread,omitempty"`
	SinceTime       string          `protobuf:"bytes,6,opt,name=sinceTime,proto3" json:"sinceTime,omitempty"`
	RecentSeconds   int64           `protobuf:"varint,7,opt,name=recentSeconds,proto3" json:"recentSeconds,omitempty"`
	CursorUpdatedAt string          `protobuf:"bytes,8,opt,name=cursorUpdatedAt,proto3" json:"cursorUpdatedAt,omitempty"`
	CursorId        int64           `protobuf:"varint,9,opt,name=cursorId,proto3" json:"cursorId,omitempty"`
	NamePrefix      string          `protobuf:"bytes,10,opt,name=namePrefix,proto3" json:"namePrefix,omitempty"`
	Status          WorkOrderStatus `protobuf:"varint,11,opt,name=status,proto3,enum=workorder.WorkOrderStatus" json:"status,omitempty"`
}

func (x *ListWorkOrderReq) Reset() {
	*x = ListWorkOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkOrderReq) ProtoMessage() {}

func (x *ListWorkOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkOrderReq.ProtoReflect.Descriptor instead.
func (*ListWorkOrderReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkOrderReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListWorkOrderReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListWorkOrderReq) GetIsTo() bool {
	if x != nil {
		return x.IsTo
	}
	return false
}

func (x *ListWorkOrderReq) GetIsUnread() bool {
	if x != nil {
		return x.IsUnread
	}
	return false
}

func (x *ListWorkOrderReq) GetSinceTime() string {
	if x != nil {
		return x.SinceTime
	}
	return ""
}

func (x *ListWorkOrderReq) GetRecentSeconds() int64 {
	if x != nil {
		return x.RecentSeconds
	}
	return 0
}

func (x *ListWorkOrderReq) GetCursorUpdatedAt() string {
	if x != nil {
		return x.CursorUpdatedAt
	}
	return ""
}

func (x *ListWorkOrderReq) GetCursorId() int64 {
	if x != nil {
		return x.CursorId
	}
	return 0
}

func (x *ListWorkOrderReq) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *ListWorkOrderReq) GetStatus() WorkOrderStatus {
	if x != nil {
		return x.Status
	}
	return WorkOrderStatus_WORK_ORDER_STATUS_UNKNOWN
}

type ListWorkOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkOrderList       []*WorkOrderInfo `protobuf:"bytes,1,rep,name=workOrderList,proto3" json:"workOrderList,omitempty"`
	Total               int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore             bool             `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	NextCursorUpdatedAt string           `protobuf:"bytes,4,opt,name=nextCursorUpdatedAt,proto3" json:"nextCursorUpdatedAt,omitempty"`
	NextCursorId        int64            `protobuf:"varint,5,opt,name=nextCursorId,proto3" json:"nextCursorId,omitempty"`
}

func (x *ListWorkOrderResp) Reset() {
	*x = ListWorkOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkOrderResp) ProtoMessage() {}

func (x *ListWorkOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkOrderResp.ProtoReflect.Descriptor instead.
func (*ListWorkOrderResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{12}
}

func (x *ListWorkOrderResp) GetWorkOrderList() []*WorkOrderInfo {
	if x != nil {
		return x.WorkOrderList
	}
	return nil
}

func (x *ListWorkOrderResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWorkOrderResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListWorkOrderResp) GetNextCursorUpdatedAt() string {
	if x != nil {
		return x.NextCursorUpdatedAt
	}
	return ""
}

func (x *ListWorkOrderResp) GetNextCursorId() int64 {
	if x != nil {
		return x.NextCursorId
	}
	return 0
}

type MarkWorkOrderReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MarkWorkOrderReadReq) Reset() {
	*x = MarkWorkOrderReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkWorkOrderReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkWorkOrderReadReq) ProtoMessage() {}

func (x *MarkWorkOrderReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkWorkOrderReadReq.ProtoReflect.Descriptor instead.
func (*MarkWorkOrderReadReq) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{13}
}

func (x *MarkWorkOrderReadReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkWorkOrderReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MarkWorkOrderReadResp) Reset() {
	*x = MarkWorkOrderReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkWorkOrderReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkWorkOrderReadResp) ProtoMessage() {}

func (x *MarkWorkOrderReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkWorkOrderReadResp.ProtoReflect.Descriptor instead.
func (*MarkWorkOrderReadResp) Descriptor() ([]byte, []int) {
	return file_workorder_proto_rawDescGZIP(), []int{14}
}

func (x *MarkWorkOrderReadResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_workorder_proto protoreflect.FileDescriptor

var file_workorder_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xc5, 0x02, 0x0a,
	0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x3e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x66,
	0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x34, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0xe6, 0x02, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73,
	0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x54, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xd9, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e,
	0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x30,
	0x0a, 0x13, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6e, 0x65, 0x78,
	0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x4d, 0x61, 0x72, 0x6b, 0x57, 0x6f, 0x72, 0x6b,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x15,
	0x4d, 0x61, 0x72, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a,
	0x6e, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x0a, 0x19, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x1b, 0x0a, 0x17, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x01, 0x12, 0x1f,
	0x0a, 0x1b, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x02, 0x2a,
	0x7d, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x1e, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x57, 0x4f,
	0x52, 0x4b, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x1f, 0x0a,
	0x1b, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x44,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x10, 0x02, 0x32, 0xe5,
	0x04, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5f, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12, 0x22, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x23, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61,
	0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5f, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12, 0x22,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x72,
	0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x50, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x4a, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x56,
	0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x1f, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x4d, 0x61, 0x72, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x53, 0x63, 0x65, 0x6e, 0x69, 0x78, 0x2f, 0x6d, 0x65,
	0x73, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f,
	0x67, 0x65, 0x6e, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workorder_proto_rawDescOnce sync.Once
	file_workorder_proto_rawDescData = file_workorder_proto_rawDesc
)

func file_workorder_proto_rawDescGZIP() []byte {
	file_workorder_proto_rawDescOnce.Do(func() {
		file_workorder_proto_rawDescData = protoimpl.X.CompressGZIP(file_workorder_proto_rawDescData)
	})
	return file_workorder_proto_rawDescData
}

var file_workorder_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workorder_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_workorder_proto_goTypes = []interface{}{
	(WorkOrderStatus)(0),             // 0: workorder.WorkOrderStatus
	(WorkOrderReadStatus)(0),         // 1: workorder.WorkOrderReadStatus
	(*WorkOrderInfo)(nil),            // 2: workorder.WorkOrderInfo
	(*CreateWorkOrderReq)(nil),       // 3: workorder.CreateWorkOrderReq
	(*CreateWorkOrderResp)(nil),      // 4: workorder.CreateWorkOrderResp
	(*UpdateWorkOrderDraftReq)(nil),  // 5: workorder.UpdateWorkOrderDraftReq
	(*UpdateWorkOrderDraftResp)(nil), // 6: workorder.UpdateWorkOrderDraftResp
	(*DeleteWorkOrderDraftReq)(nil),  // 7: workorder.DeleteWorkOrderDraftReq
	(*DeleteWorkOrderDraftResp)(nil), // 8: workorder.DeleteWorkOrderDraftResp
	(*SubmitWorkOrderReq)(nil),       // 9: workorder.SubmitWorkOrderReq
	(*SubmitWorkOrderResp)(nil),      // 10: workorder.SubmitWorkOrderResp
	(*GetWorkOrderReq)(nil),          // 11: workorder.GetWorkOrderReq
	(*GetWorkOrderResp)(nil),         // 12: workorder.GetWorkOrderResp
	(*ListWorkOrderReq)(nil),         // 13: workorder.ListWorkOrderReq
	(*ListWorkOrderResp)(nil),        // 14: workorder.ListWorkOrderResp
	(*MarkWorkOrderReadReq)(nil),     // 15: workorder.MarkWorkOrderReadReq
	(*MarkWorkOrderReadResp)(nil),    // 16: workorder.MarkWorkOrderReadResp
}
var file_workorder_proto_depIdxs = []int32{
	0,  // 0: workorder.WorkOrderInfo.status:type_name -> workorder.WorkOrderStatus
	1,  // 1: workorder.WorkOrderInfo.readStatus:type_name -> workorder.WorkOrderReadStatus
	2,  // 2: workorder.GetWorkOrderResp.workOrder:type_name -> workorder.WorkOrderInfo
	0,  // 3: workorder.ListWorkOrderReq.status:type_name -> workorder.WorkOrderStatus
	2,  // 4: workorder.ListWorkOrderResp.workOrderList:type_name -> workorder.WorkOrderInfo
	3,  // 5: workorder.WorkOrderService.CreateWorkOrder:input_type -> workorder.CreateWorkOrderReq
	5,  // 6: workorder.WorkOrderService.UpdateWorkOrderDraft:input_type -> workorder.UpdateWorkOrderDraftReq
	7,  // 7: workorder.WorkOrderService.DeleteWorkOrderDraft:input_type -> workorder.DeleteWorkOrderDraftReq
	9,  // 8: workorder.WorkOrderService.SubmitWorkOrder:input_type -> workorder.SubmitWorkOrderReq
	11, // 9: workorder.WorkOrderService.GetWorkOrder:input_type -> workorder.GetWorkOrderReq
	13, // 10: workorder.WorkOrderService.ListWorkOrder:input_type -> workorder.ListWorkOrderReq
	15, // 11: workorder.WorkOrderService.MarkWorkOrderRead:input_type -> workorder.MarkWorkOrderReadReq
	4,  // 12: workorder.WorkOrderService.CreateWorkOrder:output_type -> workorder.CreateWorkOrderResp
	6,  // 13: workorder.WorkOrderService.UpdateWorkOrderDraft:output_type -> workorder.UpdateWorkOrderDraftResp
	8,  // 14: workorder.WorkOrderService.DeleteWorkOrderDraft:output_type -> workorder.DeleteWorkOrderDraftResp
	10, // 15: workorder.WorkOrderService.SubmitWorkOrder:output_type -> workorder.SubmitWorkOrderResp
	12, // 16: workorder.WorkOrderService.GetWorkOrder:output_type -> workorder.GetWorkOrderResp
	14, // 17: workorder.WorkOrderService.ListWorkOrder:output_type -> workorder.ListWorkOrderResp
	16, // 18: workorder.WorkOrderService.MarkWorkOrderRead:output_type -> workorder.MarkWorkOrderReadResp
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_workorder_proto_init() }
func file_workorder_proto_init() {
	if File_workorder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workorder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkOrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorkOrderDraftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorkOrderDraftResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkOrderDraftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkOrderDraftResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitWorkOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitWorkOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkWorkOrderReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkWorkOrderReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workorder_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workorder_proto_goTypes,
		DependencyIndexes: file_workorder_proto_depIdxs,
		EnumInfos:         file_workorder_proto_enumTypes,
		MessageInfos:      file_workorder_proto_msgTypes,
	}.Build()
	File_workorder_proto = out.File
	file_workorder_proto_rawDesc = nil
	file_workorder_proto_goTypes = nil
	file_workorder_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type WorkOrderService interface {
	CreateWorkOrder(ctx context.Context, req *CreateWorkOrderReq) (res *CreateWorkOrderResp, err error)
	UpdateWorkOrderDraft(ctx context.Context, req *UpdateWorkOrderDraftReq) (res *UpdateWorkOrderDraftResp, err error)
	DeleteWorkOrderDraft(ctx context.Context, req *DeleteWorkOrderDraftReq) (res *DeleteWorkOrderDraftResp, err error)
	SubmitWorkOrder(ctx context.Context, req *SubmitWorkOrderReq) (res *SubmitWorkOrderResp, err error)
	GetWorkOrder(ctx context.Context, req *GetWorkOrderReq) (res *GetWorkOrderResp, err error)
	ListWorkOrder(ctx context.Context, req *ListWorkOrderReq) (res *ListWorkOrderResp, err error)
	MarkWorkOrderRead(ctx context.Context, req *MarkWorkOrderReadReq) (res *MarkWorkOrderReadResp, err error)
}
