// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package app

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *AppInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 11:
		offset, err = x.fastReadField11(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AppInfo[number], err)
}

func (x *AppInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.AppName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Cover, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.InitPrompt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.DeployKey, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.DeployedTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.Priority, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppInfo) fastReadField11(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddAppReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddAppReq[number], err)
}

func (x *AddAppReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.InitPrompt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddAppReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddAppResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddAppResp[number], err)
}

func (x *AddAppResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteAppReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteAppReq[number], err)
}

func (x *DeleteAppReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteAppResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteAppResp[number], err)
}

func (x *DeleteAppResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *UpdateAppReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateAppReq[number], err)
}

func (x *UpdateAppReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateAppReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.AppName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateAppReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Cover, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateAppReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Priority, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateAppReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.DeployKey, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateAppResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateAppResp[number], err)
}

func (x *UpdateAppResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *GetAppReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetAppReq[number], err)
}

func (x *GetAppReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GetAppResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetAppResp[number], err)
}

func (x *GetAppResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v AppInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.App = &v
	return offset, nil
}

func (x *ListAppReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListAppReq[number], err)
}

func (x *ListAppReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.PageNum, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListAppReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListAppReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.AppName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListAppReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListAppResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListAppResp[number], err)
}

func (x *ListAppResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v AppInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.AppList = append(x.AppList, &v)
	return offset, nil
}

func (x *ListAppResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppMessage) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AppMessage[number], err)
}

func (x *AppMessage) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.AppId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Role, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.IsDelete, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AppMessage) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.IsFile, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *AddMessageReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddMessageReq[number], err)
}

func (x *AddMessageReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.AppId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddMessageReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddMessageReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Role, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddMessageReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddMessageReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.IsFile, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *AddMessageResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddMessageResp[number], err)
}

func (x *AddMessageResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteMessageReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteMessageReq[number], err)
}

func (x *DeleteMessageReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteMessageResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteMessageResp[number], err)
}

func (x *DeleteMessageResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ListAppMessageReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListAppMessageReq[number], err)
}

func (x *ListAppMessageReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.AppId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListAppMessageReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListAppMessageReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.LastCreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListAppMessageResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListAppMessageResp[number], err)
}

func (x *ListAppMessageResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v AppMessage
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.MessageList = append(x.MessageList, &v)
	return offset, nil
}

func (x *ListAppMessageResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListAppMessageResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.HasMore, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *AppInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	offset += x.fastWriteField11(buf[offset:])
	return offset
}

func (x *AppInfo) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *AppInfo) fastWriteField2(buf []byte) (offset int) {
	if x.AppName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetAppName())
	return offset
}

func (x *AppInfo) fastWriteField3(buf []byte) (offset int) {
	if x.Cover == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetCover())
	return offset
}

func (x *AppInfo) fastWriteField4(buf []byte) (offset int) {
	if x.InitPrompt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetInitPrompt())
	return offset
}

func (x *AppInfo) fastWriteField6(buf []byte) (offset int) {
	if x.DeployKey == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetDeployKey())
	return offset
}

func (x *AppInfo) fastWriteField7(buf []byte) (offset int) {
	if x.DeployedTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetDeployedTime())
	return offset
}

func (x *AppInfo) fastWriteField8(buf []byte) (offset int) {
	if x.Priority == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 8, x.GetPriority())
	return offset
}

func (x *AppInfo) fastWriteField9(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 9, x.GetUserId())
	return offset
}

func (x *AppInfo) fastWriteField10(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 10, x.GetCreateTime())
	return offset
}

func (x *AppInfo) fastWriteField11(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 11, x.GetUpdateTime())
	return offset
}

func (x *AddAppReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *AddAppReq) fastWriteField1(buf []byte) (offset int) {
	if x.InitPrompt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetInitPrompt())
	return offset
}

func (x *AddAppReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetUserId())
	return offset
}

func (x *AddAppResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AddAppResp) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteAppReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteAppReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteAppResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteAppResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *UpdateAppReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *UpdateAppReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *UpdateAppReq) fastWriteField2(buf []byte) (offset int) {
	if x.AppName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetAppName())
	return offset
}

func (x *UpdateAppReq) fastWriteField3(buf []byte) (offset int) {
	if x.Cover == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetCover())
	return offset
}

func (x *UpdateAppReq) fastWriteField4(buf []byte) (offset int) {
	if x.Priority == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetPriority())
	return offset
}

func (x *UpdateAppReq) fastWriteField5(buf []byte) (offset int) {
	if x.DeployKey == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetDeployKey())
	return offset
}

func (x *UpdateAppResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *UpdateAppResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *GetAppReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetAppReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GetAppResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetAppResp) fastWriteField1(buf []byte) (offset int) {
	if x.App == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetApp())
	return offset
}

func (x *ListAppReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *ListAppReq) fastWriteField1(buf []byte) (offset int) {
	if x.PageNum == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetPageNum())
	return offset
}

func (x *ListAppReq) fastWriteField2(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetPageSize())
	return offset
}

func (x *ListAppReq) fastWriteField3(buf []byte) (offset int) {
	if x.AppName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetAppName())
	return offset
}

func (x *ListAppReq) fastWriteField4(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetUserId())
	return offset
}

func (x *ListAppResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *ListAppResp) fastWriteField1(buf []byte) (offset int) {
	if x.AppList == nil {
		return offset
	}
	for i := range x.GetAppList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetAppList()[i])
	}
	return offset
}

func (x *ListAppResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *AppMessage) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	return offset
}

func (x *AppMessage) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *AppMessage) fastWriteField2(buf []byte) (offset int) {
	if x.AppId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetAppId())
	return offset
}

func (x *AppMessage) fastWriteField3(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetUserId())
	return offset
}

func (x *AppMessage) fastWriteField4(buf []byte) (offset int) {
	if x.Role == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetRole())
	return offset
}

func (x *AppMessage) fastWriteField5(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetContent())
	return offset
}

func (x *AppMessage) fastWriteField6(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetCreateTime())
	return offset
}

func (x *AppMessage) fastWriteField7(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetUpdateTime())
	return offset
}

func (x *AppMessage) fastWriteField8(buf []byte) (offset int) {
	if x.IsDelete == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 8, x.GetIsDelete())
	return offset
}

func (x *AppMessage) fastWriteField9(buf []byte) (offset int) {
	if !x.IsFile {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 9, x.GetIsFile())
	return offset
}

func (x *AddMessageReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *AddMessageReq) fastWriteField1(buf []byte) (offset int) {
	if x.AppId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetAppId())
	return offset
}

func (x *AddMessageReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetUserId())
	return offset
}

func (x *AddMessageReq) fastWriteField3(buf []byte) (offset int) {
	if x.Role == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetRole())
	return offset
}

func (x *AddMessageReq) fastWriteField4(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetContent())
	return offset
}

func (x *AddMessageReq) fastWriteField5(buf []byte) (offset int) {
	if !x.IsFile {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 5, x.GetIsFile())
	return offset
}

func (x *AddMessageResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AddMessageResp) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteMessageReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteMessageReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteMessageResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteMessageResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *ListAppMessageReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListAppMessageReq) fastWriteField1(buf []byte) (offset int) {
	if x.AppId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetAppId())
	return offset
}

func (x *ListAppMessageReq) fastWriteField2(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetPageSize())
	return offset
}

func (x *ListAppMessageReq) fastWriteField3(buf []byte) (offset int) {
	if x.LastCreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetLastCreateTime())
	return offset
}

func (x *ListAppMessageResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListAppMessageResp) fastWriteField1(buf []byte) (offset int) {
	if x.MessageList == nil {
		return offset
	}
	for i := range x.GetMessageList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetMessageList()[i])
	}
	return offset
}

func (x *ListAppMessageResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *ListAppMessageResp) fastWriteField3(buf []byte) (offset int) {
	if !x.HasMore {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 3, x.GetHasMore())
	return offset
}

func (x *AppInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	n += x.sizeField11()
	return n
}

func (x *AppInfo) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *AppInfo) sizeField2() (n int) {
	if x.AppName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetAppName())
	return n
}

func (x *AppInfo) sizeField3() (n int) {
	if x.Cover == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetCover())
	return n
}

func (x *AppInfo) sizeField4() (n int) {
	if x.InitPrompt == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetInitPrompt())
	return n
}

func (x *AppInfo) sizeField6() (n int) {
	if x.DeployKey == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetDeployKey())
	return n
}

func (x *AppInfo) sizeField7() (n int) {
	if x.DeployedTime == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetDeployedTime())
	return n
}

func (x *AppInfo) sizeField8() (n int) {
	if x.Priority == 0 {
		return n
	}
	n += fastpb.SizeInt64(8, x.GetPriority())
	return n
}

func (x *AppInfo) sizeField9() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(9, x.GetUserId())
	return n
}

func (x *AppInfo) sizeField10() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(10, x.GetCreateTime())
	return n
}

func (x *AppInfo) sizeField11() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(11, x.GetUpdateTime())
	return n
}

func (x *AddAppReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *AddAppReq) sizeField1() (n int) {
	if x.InitPrompt == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetInitPrompt())
	return n
}

func (x *AddAppReq) sizeField2() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetUserId())
	return n
}

func (x *AddAppResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AddAppResp) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteAppReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteAppReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteAppResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteAppResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *UpdateAppReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *UpdateAppReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *UpdateAppReq) sizeField2() (n int) {
	if x.AppName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetAppName())
	return n
}

func (x *UpdateAppReq) sizeField3() (n int) {
	if x.Cover == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetCover())
	return n
}

func (x *UpdateAppReq) sizeField4() (n int) {
	if x.Priority == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetPriority())
	return n
}

func (x *UpdateAppReq) sizeField5() (n int) {
	if x.DeployKey == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetDeployKey())
	return n
}

func (x *UpdateAppResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *UpdateAppResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *GetAppReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetAppReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GetAppResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetAppResp) sizeField1() (n int) {
	if x.App == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetApp())
	return n
}

func (x *ListAppReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *ListAppReq) sizeField1() (n int) {
	if x.PageNum == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetPageNum())
	return n
}

func (x *ListAppReq) sizeField2() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetPageSize())
	return n
}

func (x *ListAppReq) sizeField3() (n int) {
	if x.AppName == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetAppName())
	return n
}

func (x *ListAppReq) sizeField4() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetUserId())
	return n
}

func (x *ListAppResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *ListAppResp) sizeField1() (n int) {
	if x.AppList == nil {
		return n
	}
	for i := range x.GetAppList() {
		n += fastpb.SizeMessage(1, x.GetAppList()[i])
	}
	return n
}

func (x *ListAppResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

func (x *AppMessage) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	return n
}

func (x *AppMessage) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *AppMessage) sizeField2() (n int) {
	if x.AppId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetAppId())
	return n
}

func (x *AppMessage) sizeField3() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetUserId())
	return n
}

func (x *AppMessage) sizeField4() (n int) {
	if x.Role == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetRole())
	return n
}

func (x *AppMessage) sizeField5() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetContent())
	return n
}

func (x *AppMessage) sizeField6() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetCreateTime())
	return n
}

func (x *AppMessage) sizeField7() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetUpdateTime())
	return n
}

func (x *AppMessage) sizeField8() (n int) {
	if x.IsDelete == 0 {
		return n
	}
	n += fastpb.SizeInt64(8, x.GetIsDelete())
	return n
}

func (x *AppMessage) sizeField9() (n int) {
	if !x.IsFile {
		return n
	}
	n += fastpb.SizeBool(9, x.GetIsFile())
	return n
}

func (x *AddMessageReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *AddMessageReq) sizeField1() (n int) {
	if x.AppId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetAppId())
	return n
}

func (x *AddMessageReq) sizeField2() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetUserId())
	return n
}

func (x *AddMessageReq) sizeField3() (n int) {
	if x.Role == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetRole())
	return n
}

func (x *AddMessageReq) sizeField4() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetContent())
	return n
}

func (x *AddMessageReq) sizeField5() (n int) {
	if !x.IsFile {
		return n
	}
	n += fastpb.SizeBool(5, x.GetIsFile())
	return n
}

func (x *AddMessageResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AddMessageResp) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteMessageReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteMessageReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteMessageResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteMessageResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *ListAppMessageReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListAppMessageReq) sizeField1() (n int) {
	if x.AppId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetAppId())
	return n
}

func (x *ListAppMessageReq) sizeField2() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetPageSize())
	return n
}

func (x *ListAppMessageReq) sizeField3() (n int) {
	if x.LastCreateTime == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetLastCreateTime())
	return n
}

func (x *ListAppMessageResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListAppMessageResp) sizeField1() (n int) {
	if x.MessageList == nil {
		return n
	}
	for i := range x.GetMessageList() {
		n += fastpb.SizeMessage(1, x.GetMessageList()[i])
	}
	return n
}

func (x *ListAppMessageResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

func (x *ListAppMessageResp) sizeField3() (n int) {
	if !x.HasMore {
		return n
	}
	n += fastpb.SizeBool(3, x.GetHasMore())
	return n
}

var fieldIDToName_AppInfo = map[int32]string{
	1:  "Id",
	2:  "AppName",
	3:  "Cover",
	4:  "InitPrompt",
	6:  "DeployKey",
	7:  "DeployedTime",
	8:  "Priority",
	9:  "UserId",
	10: "CreateTime",
	11: "UpdateTime",
}

var fieldIDToName_AddAppReq = map[int32]string{
	1: "InitPrompt",
	2: "UserId",
}

var fieldIDToName_AddAppResp = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteAppReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteAppResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_UpdateAppReq = map[int32]string{
	1: "Id",
	2: "AppName",
	3: "Cover",
	4: "Priority",
	5: "DeployKey",
}

var fieldIDToName_UpdateAppResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_GetAppReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_GetAppResp = map[int32]string{
	1: "App",
}

var fieldIDToName_ListAppReq = map[int32]string{
	1: "PageNum",
	2: "PageSize",
	3: "AppName",
	4: "UserId",
}

var fieldIDToName_ListAppResp = map[int32]string{
	1: "AppList",
	2: "Total",
}

var fieldIDToName_AppMessage = map[int32]string{
	1: "Id",
	2: "AppId",
	3: "UserId",
	4: "Role",
	5: "Content",
	6: "CreateTime",
	7: "UpdateTime",
	8: "IsDelete",
	9: "IsFile",
}

var fieldIDToName_AddMessageReq = map[int32]string{
	1: "AppId",
	2: "UserId",
	3: "Role",
	4: "Content",
	5: "IsFile",
}

var fieldIDToName_AddMessageResp = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteMessageReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteMessageResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_ListAppMessageReq = map[int32]string{
	1: "AppId",
	2: "PageSize",
	3: "LastCreateTime",
}

var fieldIDToName_ListAppMessageResp = map[int32]string{
	1: "MessageList",
	2: "Total",
	3: "HasMore",
}
