// Code generated by hertz generator. DO NOT EDIT.

package mes

import (
	mes "github.com/MoScenix/mes/app/bff/biz/handler/mes"
	"github.com/cloudwego/hertz/pkg/app/server"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_mes := root.Group("/mes", _mesMw()...)
		{
			_engineering_order := _mes.Group("/engineering-order", _engineering_orderMw()...)
			_engineering_order.GET("/get", append(_getengineeringorderMw(), mes.GetEngineeringOrder)...)
			_engineering_order.POST("/list", append(_listengineeringorderMw(), mes.ListEngineeringOrder)...)
			_engineering_order.POST("/submit", append(_submitengineeringorderMw(), mes.SubmitEngineeringOrder)...)
			{
				_draft := _engineering_order.Group("/draft", _draftMw()...)
				_draft.POST("/create", append(_createengineeringorderdraftMw(), mes.CreateEngineeringOrderDraft)...)
				_draft.POST("/delete", append(_deleteengineeringorderdraftMw(), mes.DeleteEngineeringOrderDraft)...)
				_draft.POST("/update", append(_updateengineeringorderdraftMw(), mes.UpdateEngineeringOrderDraft)...)
			}
		}
		{
			_inventory_flow := _mes.Group("/inventory-flow", _inventory_flowMw()...)
			_inventory_flow.POST("/audit", append(_auditinventoryflowMw(), mes.AuditInventoryFlow)...)
			_inventory_flow.POST("/complete", append(_completeinventoryflowMw(), mes.CompleteInventoryFlow)...)
			_inventory_flow.GET("/get", append(_getinventoryflowMw(), mes.GetInventoryFlow)...)
			_inventory_flow.POST("/list", append(_listinventoryflowMw(), mes.ListInventoryFlow)...)
			_inventory_flow.POST("/submit", append(_submitinventoryflowMw(), mes.SubmitInventoryFlow)...)
			{
				_draft0 := _inventory_flow.Group("/draft", _draft0Mw()...)
				_draft0.POST("/create", append(_createinventoryflowdraftMw(), mes.CreateInventoryFlowDraft)...)
				_draft0.POST("/delete", append(_deleteinventoryflowdraftMw(), mes.DeleteInventoryFlowDraft)...)
				_draft0.POST("/update", append(_updateinventoryflowdraftMw(), mes.UpdateInventoryFlowDraft)...)
			}
		}
		{
			_item := _mes.Group("/item", _itemMw()...)
			_item.POST("/add", append(_additemMw(), mes.AddItem)...)
			_item.GET("/get", append(_getitemMw(), mes.GetItem)...)
			_item.POST("/list", append(_listitemMw(), mes.ListItem)...)
			_item.GET("/search", append(_searchitemsMw(), mes.SearchItems)...)
			_item.POST("/update", append(_updateitemMw(), mes.UpdateItem)...)
		}
		{
			_item_unit := _mes.Group("/item-unit", _item_unitMw()...)
			_item_unit.POST("/add", append(_additemunitMw(), mes.AddItemUnit)...)
			_item_unit.GET("/get", append(_getitemunitMw(), mes.GetItemUnit)...)
			_item_unit.POST("/list", append(_listitemunitMw(), mes.ListItemUnit)...)
			{
				_status := _item_unit.Group("/status", _statusMw()...)
				_status.POST("/update", append(_updateitemunitstatusMw(), mes.UpdateItemUnitStatus)...)
			}
		}
		{
			_process := _mes.Group("/process", _processMw()...)
			_process.GET("/get", append(_getprocessMw(), mes.GetProcess)...)
			_process.POST("/list", append(_listprocessMw(), mes.ListProcess)...)
			_process.POST("/submit", append(_submitprocessMw(), mes.SubmitProcess)...)
			{
				_draft1 := _process.Group("/draft", _draft1Mw()...)
				_draft1.POST("/create", append(_createprocessdraftMw(), mes.CreateProcessDraft)...)
				_draft1.POST("/delete", append(_deleteprocessdraftMw(), mes.DeleteProcessDraft)...)
				_draft1.POST("/update", append(_updateprocessdraftMw(), mes.UpdateProcessDraft)...)
			}
		}
		{
			_work_order := _mes.Group("/work-order", _work_orderMw()...)
			_work_order.GET("/get", append(_getworkorderMw(), mes.GetWorkOrder)...)
			_work_order.POST("/list", append(_listworkorderMw(), mes.ListWorkOrder)...)
			_work_order.POST("/read", append(_markworkorderreadMw(), mes.MarkWorkOrderRead)...)
			_work_order.POST("/submit", append(_submitworkorderMw(), mes.SubmitWorkOrder)...)
			{
				_draft2 := _work_order.Group("/draft", _draft2Mw()...)
				_draft2.POST("/create", append(_createworkorderdraftMw(), mes.CreateWorkOrderDraft)...)
				_draft2.POST("/delete", append(_deleteworkorderdraftMw(), mes.DeleteWorkOrderDraft)...)
				_draft2.POST("/update", append(_updateworkorderdraftMw(), mes.UpdateWorkOrderDraft)...)
			}
		}
	}
}
