// Code generated by hertz generator.

package mes

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _engineering_orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createengineeringorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getengineeringorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listengineeringorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateengineeringorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _inventory_flowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditinventoryflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinventoryflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listinventoryflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitinventoryflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createinventoryflowdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteinventoryflowdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateinventoryflowdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _itemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _additemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _item_unitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _additemunitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemunitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listitemunitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateitemunitstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _work_orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listworkorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markworkorderreadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitworkorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draft0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createworkorderdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteworkorderdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateworkorderdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitengineeringorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createengineeringorderdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteengineeringorderdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateengineeringorderdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprocessMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listprocessMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitprocessMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draft1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createprocessdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteprocessdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprocessdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draft2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completeinventoryflowMw() []app.HandlerFunc {
	// your code...
	return nil
}
