// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package document

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *ParsePDFToTextReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ParsePDFToTextReq[number], err)
}

func (x *ParsePDFToTextReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ParsePDFToTextReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FileId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ParsePDFToTextResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ParsePDFToTextResp[number], err)
}

func (x *ParsePDFToTextResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.FileId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ParsePDFToTextResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.TextFilename, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParsePDFToTextResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.TextSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_IndexTextFileReq[number], err)
}

func (x *IndexTextFileReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FileId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.MinSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.MaxSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_IndexTextFileResp[number], err)
}

func (x *IndexTextFileResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.FileId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ChunkCount, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *IndexTextFileResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ParentCount, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SearchFileReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchFileReq[number], err)
}

func (x *SearchFileReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SearchFileReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FileId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SearchFileReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Query, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchFileReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.TopK, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SearchFileResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchFileResp[number], err)
}

func (x *SearchFileResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	offset, err = fastpb.ReadList(buf, _type,
		func(buf []byte, _type int8) (n int, err error) {
			var v int64
			v, offset, err = fastpb.ReadInt64(buf, _type)
			if err != nil {
				return offset, err
			}
			x.ParentIds = append(x.ParentIds, v)
			return offset, err
		})
	return offset, err
}

func (x *DeleteProjectFileDataReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteProjectFileDataReq[number], err)
}

func (x *DeleteProjectFileDataReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteProjectFileDataResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteProjectFileDataResp[number], err)
}

func (x *DeleteProjectFileDataResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ParsePDFToTextReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *ParsePDFToTextReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *ParsePDFToTextReq) fastWriteField2(buf []byte) (offset int) {
	if x.FileId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetFileId())
	return offset
}

func (x *ParsePDFToTextResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ParsePDFToTextResp) fastWriteField1(buf []byte) (offset int) {
	if x.FileId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetFileId())
	return offset
}

func (x *ParsePDFToTextResp) fastWriteField2(buf []byte) (offset int) {
	if x.TextFilename == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetTextFilename())
	return offset
}

func (x *ParsePDFToTextResp) fastWriteField3(buf []byte) (offset int) {
	if x.TextSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetTextSize())
	return offset
}

func (x *IndexTextFileReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *IndexTextFileReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *IndexTextFileReq) fastWriteField2(buf []byte) (offset int) {
	if x.FileId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetFileId())
	return offset
}

func (x *IndexTextFileReq) fastWriteField3(buf []byte) (offset int) {
	if x.MinSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetMinSize())
	return offset
}

func (x *IndexTextFileReq) fastWriteField4(buf []byte) (offset int) {
	if x.MaxSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetMaxSize())
	return offset
}

func (x *IndexTextFileResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *IndexTextFileResp) fastWriteField1(buf []byte) (offset int) {
	if x.FileId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetFileId())
	return offset
}

func (x *IndexTextFileResp) fastWriteField2(buf []byte) (offset int) {
	if x.ChunkCount == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetChunkCount())
	return offset
}

func (x *IndexTextFileResp) fastWriteField3(buf []byte) (offset int) {
	if x.ParentCount == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetParentCount())
	return offset
}

func (x *SearchFileReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *SearchFileReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *SearchFileReq) fastWriteField2(buf []byte) (offset int) {
	if x.FileId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetFileId())
	return offset
}

func (x *SearchFileReq) fastWriteField3(buf []byte) (offset int) {
	if x.Query == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetQuery())
	return offset
}

func (x *SearchFileReq) fastWriteField4(buf []byte) (offset int) {
	if x.TopK == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetTopK())
	return offset
}

func (x *SearchFileResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SearchFileResp) fastWriteField1(buf []byte) (offset int) {
	if len(x.ParentIds) == 0 {
		return offset
	}
	offset += fastpb.WriteListPacked(buf[offset:], 1, len(x.GetParentIds()),
		func(buf []byte, numTagOrKey, numIdxOrVal int32) int {
			offset := 0
			offset += fastpb.WriteInt64(buf[offset:], numTagOrKey, x.GetParentIds()[numIdxOrVal])
			return offset
		})
	return offset
}

func (x *DeleteProjectFileDataReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteProjectFileDataReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *DeleteProjectFileDataResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteProjectFileDataResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *ParsePDFToTextReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *ParsePDFToTextReq) sizeField1() (n int) {
	if x.ProjectId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetProjectId())
	return n
}

func (x *ParsePDFToTextReq) sizeField2() (n int) {
	if x.FileId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetFileId())
	return n
}

func (x *ParsePDFToTextResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ParsePDFToTextResp) sizeField1() (n int) {
	if x.FileId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetFileId())
	return n
}

func (x *ParsePDFToTextResp) sizeField2() (n int) {
	if x.TextFilename == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetTextFilename())
	return n
}

func (x *ParsePDFToTextResp) sizeField3() (n int) {
	if x.TextSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetTextSize())
	return n
}

func (x *IndexTextFileReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *IndexTextFileReq) sizeField1() (n int) {
	if x.ProjectId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetProjectId())
	return n
}

func (x *IndexTextFileReq) sizeField2() (n int) {
	if x.FileId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetFileId())
	return n
}

func (x *IndexTextFileReq) sizeField3() (n int) {
	if x.MinSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetMinSize())
	return n
}

func (x *IndexTextFileReq) sizeField4() (n int) {
	if x.MaxSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetMaxSize())
	return n
}

func (x *IndexTextFileResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *IndexTextFileResp) sizeField1() (n int) {
	if x.FileId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetFileId())
	return n
}

func (x *IndexTextFileResp) sizeField2() (n int) {
	if x.ChunkCount == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetChunkCount())
	return n
}

func (x *IndexTextFileResp) sizeField3() (n int) {
	if x.ParentCount == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetParentCount())
	return n
}

func (x *SearchFileReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *SearchFileReq) sizeField1() (n int) {
	if x.ProjectId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetProjectId())
	return n
}

func (x *SearchFileReq) sizeField2() (n int) {
	if x.FileId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetFileId())
	return n
}

func (x *SearchFileReq) sizeField3() (n int) {
	if x.Query == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetQuery())
	return n
}

func (x *SearchFileReq) sizeField4() (n int) {
	if x.TopK == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetTopK())
	return n
}

func (x *SearchFileResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SearchFileResp) sizeField1() (n int) {
	if len(x.ParentIds) == 0 {
		return n
	}
	n += fastpb.SizeListPacked(1, len(x.GetParentIds()),
		func(numTagOrKey, numIdxOrVal int32) int {
			n := 0
			n += fastpb.SizeInt64(numTagOrKey, x.GetParentIds()[numIdxOrVal])
			return n
		})
	return n
}

func (x *DeleteProjectFileDataReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteProjectFileDataReq) sizeField1() (n int) {
	if x.ProjectId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetProjectId())
	return n
}

func (x *DeleteProjectFileDataResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteProjectFileDataResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

var fieldIDToName_ParsePDFToTextReq = map[int32]string{
	1: "ProjectId",
	2: "FileId",
}

var fieldIDToName_ParsePDFToTextResp = map[int32]string{
	1: "FileId",
	2: "TextFilename",
	3: "TextSize",
}

var fieldIDToName_IndexTextFileReq = map[int32]string{
	1: "ProjectId",
	2: "FileId",
	3: "MinSize",
	4: "MaxSize",
}

var fieldIDToName_IndexTextFileResp = map[int32]string{
	1: "FileId",
	2: "ChunkCount",
	3: "ParentCount",
}

var fieldIDToName_SearchFileReq = map[int32]string{
	1: "ProjectId",
	2: "FileId",
	3: "Query",
	4: "TopK",
}

var fieldIDToName_SearchFileResp = map[int32]string{
	1: "ParentIds",
}

var fieldIDToName_DeleteProjectFileDataReq = map[int32]string{
	1: "ProjectId",
}

var fieldIDToName_DeleteProjectFileDataResp = map[int32]string{
	1: "Success",
}
