// Code generated by Kitex v0.9.1. DO NOT EDIT.

package appservice

import (
	"context"
	"errors"

	app "github.com/MoScenix/mes/rpc_gen/kitex_gen/app"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddApp": kitex.NewMethodInfo(
		addAppHandler,
		newAddAppArgs,
		newAddAppResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteApp": kitex.NewMethodInfo(
		deleteAppHandler,
		newDeleteAppArgs,
		newDeleteAppResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateApp": kitex.NewMethodInfo(
		updateAppHandler,
		newUpdateAppArgs,
		newUpdateAppResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetApp": kitex.NewMethodInfo(
		getAppHandler,
		newGetAppArgs,
		newGetAppResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListApp": kitex.NewMethodInfo(
		listAppHandler,
		newListAppArgs,
		newListAppResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddMessage": kitex.NewMethodInfo(
		addMessageHandler,
		newAddMessageArgs,
		newAddMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteMessage": kitex.NewMethodInfo(
		deleteMessageHandler,
		newDeleteMessageArgs,
		newDeleteMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListAppMessage": kitex.NewMethodInfo(
		listAppMessageHandler,
		newListAppMessageArgs,
		newListAppMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	appServiceServiceInfo                = NewServiceInfo()
	appServiceServiceInfoForClient       = NewServiceInfoForClient()
	appServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return appServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return appServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return appServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AppService"
	handlerType := (*app.AppService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "app",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func addAppHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.AddAppReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).AddApp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddAppArgs:
		success, err := handler.(app.AppService).AddApp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddAppResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddAppArgs() interface{} {
	return &AddAppArgs{}
}

func newAddAppResult() interface{} {
	return &AddAppResult{}
}

type AddAppArgs struct {
	Req *app.AddAppReq
}

func (p *AddAppArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.AddAppReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddAppArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddAppArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddAppArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddAppArgs) Unmarshal(in []byte) error {
	msg := new(app.AddAppReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddAppArgs_Req_DEFAULT *app.AddAppReq

func (p *AddAppArgs) GetReq() *app.AddAppReq {
	if !p.IsSetReq() {
		return AddAppArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddAppArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddAppResult struct {
	Success *app.AddAppResp
}

var AddAppResult_Success_DEFAULT *app.AddAppResp

func (p *AddAppResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.AddAppResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddAppResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddAppResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddAppResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddAppResult) Unmarshal(in []byte) error {
	msg := new(app.AddAppResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddAppResult) GetSuccess() *app.AddAppResp {
	if !p.IsSetSuccess() {
		return AddAppResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.AddAppResp)
}

func (p *AddAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddAppResult) GetResult() interface{} {
	return p.Success
}

func deleteAppHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.DeleteAppReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).DeleteApp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteAppArgs:
		success, err := handler.(app.AppService).DeleteApp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteAppResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteAppArgs() interface{} {
	return &DeleteAppArgs{}
}

func newDeleteAppResult() interface{} {
	return &DeleteAppResult{}
}

type DeleteAppArgs struct {
	Req *app.DeleteAppReq
}

func (p *DeleteAppArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.DeleteAppReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteAppArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteAppArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteAppArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteAppArgs) Unmarshal(in []byte) error {
	msg := new(app.DeleteAppReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteAppArgs_Req_DEFAULT *app.DeleteAppReq

func (p *DeleteAppArgs) GetReq() *app.DeleteAppReq {
	if !p.IsSetReq() {
		return DeleteAppArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteAppArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteAppResult struct {
	Success *app.DeleteAppResp
}

var DeleteAppResult_Success_DEFAULT *app.DeleteAppResp

func (p *DeleteAppResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.DeleteAppResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteAppResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteAppResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteAppResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteAppResult) Unmarshal(in []byte) error {
	msg := new(app.DeleteAppResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteAppResult) GetSuccess() *app.DeleteAppResp {
	if !p.IsSetSuccess() {
		return DeleteAppResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.DeleteAppResp)
}

func (p *DeleteAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteAppResult) GetResult() interface{} {
	return p.Success
}

func updateAppHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.UpdateAppReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).UpdateApp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateAppArgs:
		success, err := handler.(app.AppService).UpdateApp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateAppResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateAppArgs() interface{} {
	return &UpdateAppArgs{}
}

func newUpdateAppResult() interface{} {
	return &UpdateAppResult{}
}

type UpdateAppArgs struct {
	Req *app.UpdateAppReq
}

func (p *UpdateAppArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.UpdateAppReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateAppArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateAppArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateAppArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateAppArgs) Unmarshal(in []byte) error {
	msg := new(app.UpdateAppReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateAppArgs_Req_DEFAULT *app.UpdateAppReq

func (p *UpdateAppArgs) GetReq() *app.UpdateAppReq {
	if !p.IsSetReq() {
		return UpdateAppArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateAppArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateAppResult struct {
	Success *app.UpdateAppResp
}

var UpdateAppResult_Success_DEFAULT *app.UpdateAppResp

func (p *UpdateAppResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.UpdateAppResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateAppResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateAppResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateAppResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateAppResult) Unmarshal(in []byte) error {
	msg := new(app.UpdateAppResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateAppResult) GetSuccess() *app.UpdateAppResp {
	if !p.IsSetSuccess() {
		return UpdateAppResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.UpdateAppResp)
}

func (p *UpdateAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateAppResult) GetResult() interface{} {
	return p.Success
}

func getAppHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.GetAppReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).GetApp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetAppArgs:
		success, err := handler.(app.AppService).GetApp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetAppResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetAppArgs() interface{} {
	return &GetAppArgs{}
}

func newGetAppResult() interface{} {
	return &GetAppResult{}
}

type GetAppArgs struct {
	Req *app.GetAppReq
}

func (p *GetAppArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.GetAppReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetAppArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetAppArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetAppArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetAppArgs) Unmarshal(in []byte) error {
	msg := new(app.GetAppReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetAppArgs_Req_DEFAULT *app.GetAppReq

func (p *GetAppArgs) GetReq() *app.GetAppReq {
	if !p.IsSetReq() {
		return GetAppArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetAppArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetAppResult struct {
	Success *app.GetAppResp
}

var GetAppResult_Success_DEFAULT *app.GetAppResp

func (p *GetAppResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.GetAppResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetAppResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetAppResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetAppResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetAppResult) Unmarshal(in []byte) error {
	msg := new(app.GetAppResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetAppResult) GetSuccess() *app.GetAppResp {
	if !p.IsSetSuccess() {
		return GetAppResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.GetAppResp)
}

func (p *GetAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetAppResult) GetResult() interface{} {
	return p.Success
}

func listAppHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.ListAppReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).ListApp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListAppArgs:
		success, err := handler.(app.AppService).ListApp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListAppResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListAppArgs() interface{} {
	return &ListAppArgs{}
}

func newListAppResult() interface{} {
	return &ListAppResult{}
}

type ListAppArgs struct {
	Req *app.ListAppReq
}

func (p *ListAppArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.ListAppReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListAppArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListAppArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListAppArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListAppArgs) Unmarshal(in []byte) error {
	msg := new(app.ListAppReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListAppArgs_Req_DEFAULT *app.ListAppReq

func (p *ListAppArgs) GetReq() *app.ListAppReq {
	if !p.IsSetReq() {
		return ListAppArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListAppArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListAppResult struct {
	Success *app.ListAppResp
}

var ListAppResult_Success_DEFAULT *app.ListAppResp

func (p *ListAppResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.ListAppResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListAppResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListAppResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListAppResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListAppResult) Unmarshal(in []byte) error {
	msg := new(app.ListAppResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListAppResult) GetSuccess() *app.ListAppResp {
	if !p.IsSetSuccess() {
		return ListAppResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.ListAppResp)
}

func (p *ListAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListAppResult) GetResult() interface{} {
	return p.Success
}

func addMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.AddMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).AddMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddMessageArgs:
		success, err := handler.(app.AppService).AddMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddMessageArgs() interface{} {
	return &AddMessageArgs{}
}

func newAddMessageResult() interface{} {
	return &AddMessageResult{}
}

type AddMessageArgs struct {
	Req *app.AddMessageReq
}

func (p *AddMessageArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.AddMessageReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddMessageArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddMessageArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddMessageArgs) Unmarshal(in []byte) error {
	msg := new(app.AddMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddMessageArgs_Req_DEFAULT *app.AddMessageReq

func (p *AddMessageArgs) GetReq() *app.AddMessageReq {
	if !p.IsSetReq() {
		return AddMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddMessageResult struct {
	Success *app.AddMessageResp
}

var AddMessageResult_Success_DEFAULT *app.AddMessageResp

func (p *AddMessageResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.AddMessageResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddMessageResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddMessageResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddMessageResult) Unmarshal(in []byte) error {
	msg := new(app.AddMessageResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddMessageResult) GetSuccess() *app.AddMessageResp {
	if !p.IsSetSuccess() {
		return AddMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.AddMessageResp)
}

func (p *AddMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddMessageResult) GetResult() interface{} {
	return p.Success
}

func deleteMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.DeleteMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).DeleteMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteMessageArgs:
		success, err := handler.(app.AppService).DeleteMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteMessageArgs() interface{} {
	return &DeleteMessageArgs{}
}

func newDeleteMessageResult() interface{} {
	return &DeleteMessageResult{}
}

type DeleteMessageArgs struct {
	Req *app.DeleteMessageReq
}

func (p *DeleteMessageArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.DeleteMessageReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteMessageArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteMessageArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteMessageArgs) Unmarshal(in []byte) error {
	msg := new(app.DeleteMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteMessageArgs_Req_DEFAULT *app.DeleteMessageReq

func (p *DeleteMessageArgs) GetReq() *app.DeleteMessageReq {
	if !p.IsSetReq() {
		return DeleteMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteMessageResult struct {
	Success *app.DeleteMessageResp
}

var DeleteMessageResult_Success_DEFAULT *app.DeleteMessageResp

func (p *DeleteMessageResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.DeleteMessageResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteMessageResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteMessageResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteMessageResult) Unmarshal(in []byte) error {
	msg := new(app.DeleteMessageResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteMessageResult) GetSuccess() *app.DeleteMessageResp {
	if !p.IsSetSuccess() {
		return DeleteMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.DeleteMessageResp)
}

func (p *DeleteMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteMessageResult) GetResult() interface{} {
	return p.Success
}

func listAppMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(app.ListAppMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(app.AppService).ListAppMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListAppMessageArgs:
		success, err := handler.(app.AppService).ListAppMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListAppMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListAppMessageArgs() interface{} {
	return &ListAppMessageArgs{}
}

func newListAppMessageResult() interface{} {
	return &ListAppMessageResult{}
}

type ListAppMessageArgs struct {
	Req *app.ListAppMessageReq
}

func (p *ListAppMessageArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(app.ListAppMessageReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListAppMessageArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListAppMessageArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListAppMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListAppMessageArgs) Unmarshal(in []byte) error {
	msg := new(app.ListAppMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListAppMessageArgs_Req_DEFAULT *app.ListAppMessageReq

func (p *ListAppMessageArgs) GetReq() *app.ListAppMessageReq {
	if !p.IsSetReq() {
		return ListAppMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListAppMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListAppMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListAppMessageResult struct {
	Success *app.ListAppMessageResp
}

var ListAppMessageResult_Success_DEFAULT *app.ListAppMessageResp

func (p *ListAppMessageResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(app.ListAppMessageResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListAppMessageResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListAppMessageResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListAppMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListAppMessageResult) Unmarshal(in []byte) error {
	msg := new(app.ListAppMessageResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListAppMessageResult) GetSuccess() *app.ListAppMessageResp {
	if !p.IsSetSuccess() {
		return ListAppMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListAppMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*app.ListAppMessageResp)
}

func (p *ListAppMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListAppMessageResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddApp(ctx context.Context, Req *app.AddAppReq) (r *app.AddAppResp, err error) {
	var _args AddAppArgs
	_args.Req = Req
	var _result AddAppResult
	if err = p.c.Call(ctx, "AddApp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteApp(ctx context.Context, Req *app.DeleteAppReq) (r *app.DeleteAppResp, err error) {
	var _args DeleteAppArgs
	_args.Req = Req
	var _result DeleteAppResult
	if err = p.c.Call(ctx, "DeleteApp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateApp(ctx context.Context, Req *app.UpdateAppReq) (r *app.UpdateAppResp, err error) {
	var _args UpdateAppArgs
	_args.Req = Req
	var _result UpdateAppResult
	if err = p.c.Call(ctx, "UpdateApp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetApp(ctx context.Context, Req *app.GetAppReq) (r *app.GetAppResp, err error) {
	var _args GetAppArgs
	_args.Req = Req
	var _result GetAppResult
	if err = p.c.Call(ctx, "GetApp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListApp(ctx context.Context, Req *app.ListAppReq) (r *app.ListAppResp, err error) {
	var _args ListAppArgs
	_args.Req = Req
	var _result ListAppResult
	if err = p.c.Call(ctx, "ListApp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddMessage(ctx context.Context, Req *app.AddMessageReq) (r *app.AddMessageResp, err error) {
	var _args AddMessageArgs
	_args.Req = Req
	var _result AddMessageResult
	if err = p.c.Call(ctx, "AddMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteMessage(ctx context.Context, Req *app.DeleteMessageReq) (r *app.DeleteMessageResp, err error) {
	var _args DeleteMessageArgs
	_args.Req = Req
	var _result DeleteMessageResult
	if err = p.c.Call(ctx, "DeleteMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAppMessage(ctx context.Context, Req *app.ListAppMessageReq) (r *app.ListAppMessageResp, err error) {
	var _args ListAppMessageArgs
	_args.Req = Req
	var _result ListAppMessageResult
	if err = p.c.Call(ctx, "ListAppMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
