// Code generated by Kitex v0.9.1. DO NOT EDIT.

package appservice

import (
	"context"

	app "github.com/MoScenix/mes/rpc_gen/kitex_gen/app"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddApp(ctx context.Context, Req *app.AddAppReq, callOptions ...callopt.Option) (r *app.AddAppResp, err error)
	DeleteApp(ctx context.Context, Req *app.DeleteAppReq, callOptions ...callopt.Option) (r *app.DeleteAppResp, err error)
	UpdateApp(ctx context.Context, Req *app.UpdateAppReq, callOptions ...callopt.Option) (r *app.UpdateAppResp, err error)
	GetApp(ctx context.Context, Req *app.GetAppReq, callOptions ...callopt.Option) (r *app.GetAppResp, err error)
	ListApp(ctx context.Context, Req *app.ListAppReq, callOptions ...callopt.Option) (r *app.ListAppResp, err error)
	AddMessage(ctx context.Context, Req *app.AddMessageReq, callOptions ...callopt.Option) (r *app.AddMessageResp, err error)
	DeleteMessage(ctx context.Context, Req *app.DeleteMessageReq, callOptions ...callopt.Option) (r *app.DeleteMessageResp, err error)
	ListAppMessage(ctx context.Context, Req *app.ListAppMessageReq, callOptions ...callopt.Option) (r *app.ListAppMessageResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAppServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAppServiceClient struct {
	*kClient
}

func (p *kAppServiceClient) AddApp(ctx context.Context, Req *app.AddAppReq, callOptions ...callopt.Option) (r *app.AddAppResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddApp(ctx, Req)
}

func (p *kAppServiceClient) DeleteApp(ctx context.Context, Req *app.DeleteAppReq, callOptions ...callopt.Option) (r *app.DeleteAppResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteApp(ctx, Req)
}

func (p *kAppServiceClient) UpdateApp(ctx context.Context, Req *app.UpdateAppReq, callOptions ...callopt.Option) (r *app.UpdateAppResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateApp(ctx, Req)
}

func (p *kAppServiceClient) GetApp(ctx context.Context, Req *app.GetAppReq, callOptions ...callopt.Option) (r *app.GetAppResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetApp(ctx, Req)
}

func (p *kAppServiceClient) ListApp(ctx context.Context, Req *app.ListAppReq, callOptions ...callopt.Option) (r *app.ListAppResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListApp(ctx, Req)
}

func (p *kAppServiceClient) AddMessage(ctx context.Context, Req *app.AddMessageReq, callOptions ...callopt.Option) (r *app.AddMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddMessage(ctx, Req)
}

func (p *kAppServiceClient) DeleteMessage(ctx context.Context, Req *app.DeleteMessageReq, callOptions ...callopt.Option) (r *app.DeleteMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMessage(ctx, Req)
}

func (p *kAppServiceClient) ListAppMessage(ctx context.Context, Req *app.ListAppMessageReq, callOptions ...callopt.Option) (r *app.ListAppMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAppMessage(ctx, Req)
}
