// Code generated by hertz generator.

package app

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deployappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteappbyadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateappbyadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getappvobyidbyadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listappvobypagebyadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _genMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chattogencodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadappcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getappvobyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _goodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _page0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgoodappvobypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _myMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _page1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmyappvobypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chathistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admin0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _page2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listallchathistorybypageforadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletechathistorybyadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _app0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listappchathistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _answeraiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelaiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listaieventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pushaiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaistateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitaiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addfileMw() []app.HandlerFunc {
	// your code...
	return nil
}
